### ISSUE TITLE
Hide link destination in Link Inspector

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1001]
From a customer: I want to be able to hide the destination URL from the [link inspector](https://dub.co/tools/inspector).

For instance, I have a form in which I use Dub for gating access (password, time and date, IP geo-location).

**Comment by UsmanDev09** [comment]
I can work on this! @steven-tey

**Comment by Pratham271** [comment]
<img width="713" alt="Screenshot 2024-07-24 at 3 46 30 PM" src="https://github.com/user-attachments/assets/06a4a99f-8318-4a15-9b21-fc87c2b1b234">
@steven-tey are you talking about the highlighted links to be hidden

**Comment by kaerez** [comment]
The requirement is to add a checkbox for custom domains (free and paying accounts) and for free domains (paying accounts only), which will restrict the destination from being viewable in the inspector (and the inspector DOM).

**Comment by Pratham271** [comment]
If they are not showing on link inspector then I guess they wouldn't be visible on the DOM inspector except the logo image which will be https://link.com/favicon.ico this is what needs to be hidden in the DOM

**Comment by steven-tey** [comment]
@Pratham271 I think we need to disable this on the server side for links that are password protected

**Comment by Pratham271** [comment]
@steven-tey so we have to do it for all password protected links or just for the paid customers and also the checkbox thingy that @kaerez mentioned?

**Comment by kaerez** [comment]
@Pratham271  I think that password protected links are already blocked.
The DOM reference is to ensure the target is also not provided by the backend to the frontend and simply hidden from view.
I think we need to add it as a checkbox, as recommended above.

**Comment by Pratham271** [comment]
@kaerez thanks for the clearance and confirmation. Starting it now

**Comment by steven-tey** [comment]
> @steven-tey so we have to do it for all password protected links or just for the paid customers and also the checkbox thingy that @kaerez mentioned?

I believe only paid customers can create password-protected links atm, so just checking if the link is password protection should be enough!

**Comment by kaerez** [comment]
Or cloaked
  
On Mon, Jul 29, 2024 at 08:45, Steven Tey ***@***.***&gt; wrote:  
@steven-tey so we have to do it for all password protected links or just for the paid customers and also the checkbox thingy that @kaerez mentioned?

I believe only paid customers can create password-protected links atm, so just checking if the link is password protection should be enough!

**Comment by Pratham271** [comment]
@steven-tey @kaerez is the checkbox fine or should I place it outside the container
<img width="1207" alt="Screenshot 2024-08-01 at 2 32 39 PM" src="https://github.com/user-attachments/assets/1c6c8661-038f-45f0-a718-cbeb4f592eed">

**Comment by steven-tey** [comment]
Actually, just realized that [password-protected links](https://dub.co/help/article/password-protected-links) are hidden from the link inspector by default. 

https://github.com/user-attachments/assets/6f2abcd3-1457-4720-a395-ee8ef6d49e80

Will be closing this issue for now – sorry for the false alarm here guys!

**Comment by Pratham271** [comment]
But @kaerez suggestion is not yet implemented that user can specify some links to be hidden from the dom inspector
