### ISSUE TITLE
Docs: Self hosting guidance seems misaligned to license

### ISSUE THREAD

**Issue by ssddanbrown** [dubinc/dub#1015]
Hello, When browsing the self-hosted docs I noticed [the following text](https://github.com/dubinc/dub/blob/2e907aed9a82954957cd1ebc1044930e4728c1b9/apps/docs/self-hosting.mdx?plain=1#L42):

> First, clone the [Dub repo](https://d.to/github) into a public GitHub repository. If you are planning to distribute the code, make sure to keep the source code public to comply with our [AGPLv3 license](https://d.to/license).

I don't really see why it specifies a "public GitHub repository"? Especially as you'd be generally cloning it down for local use which is reflected by the command immediately following this, so it seems a bit out of place?

Secondly (I am not a legal expert btw) I don't believe there's anything specifically in the AGPLv3 which requires the source code to remain public, it just needs to be accessible to those that the application is distributed to (where distribution includes web use in that case).  If you need to specifically state the distribution requirements for sass offerings (which is what I assume you might be concerned about), i feel a more accurate rendition of this line would be something like:

> First, clone the [Dub repo](https://d.to/github). If you are planning to provide the application as a service, make sure to provide source access (including modifications) to users of that service under the same freedoms so you remain in compliance with the [AGPLv3 license](https://d.to/license).

**Comment by steven-tey** [comment]
Great callout, thank you! Just updated that to:

> If you are planning to distribute the code or allow users to interact with the code remotely (e.g., as part of a hosted application), make sure to provide source access (including modifications) as required by the [AGPLv3 license](https://d.to/license)

**Comment by ssddanbrown** [comment]
Thanks @steven-tey for being receptive to feedback on this, and for helping to avoid misrepresentation of the AGPL, it is much appreciated!
