### ISSUE TITLE
[ FIX ] Popover Remains Visible Over Modals When Triggered by Keyboard Shortcuts

### ISSUE THREAD

**Issue by senthil-k8s** [dubinc/dub#1023]
### Description

When using keyboard shortcuts to trigger various modals (e.g., Add/Edit, Duplicate, QR Code, Archive, Transfer), the popover that appears upon selection or when the popover is open does not automatically hide. This results in the popover overlaying the modal, which can obscure content and interfere with user interactions.

### ScreenShot 
<img width="1444" alt="Screenshot 2024-06-28 at 10 35 40 PM" src="https://github.com/dubinc/dub/assets/93466587/6b8dd392-c4e6-4406-884c-1c83d22ad328">

**Comment by steven-tey** [comment]
Thanks for reporting this and for the PR @senthil-k8s!

Unfortunately GH is not letting me merge this – do you want to create a new PR so we can try to merge it again?
