### ISSUE TITLE
Domain dub.sh not found for local setup

### ISSUE THREAD

**Issue by vaishak10** [dubinc/dub#1025]
Hey there,
After setting up the repo in local was able to navigate through the application. 
Followed all the steps as mentioned in the documentation: https://dub.co/docs/local-development#introduction
Didn't face any issue until I found a error while trying to navigate via the link created. As shown in the video it doesn't take me to the link designated to the dub link, instead takes me to the link provided in the prod environment.

https://github.com/dubinc/dub/assets/52874416/8b59abd5-81c1-44d3-853b-2025a06e18c2

What can be the fix for this?

**Comment by devkiran** [comment]
This is expected and `dub.sh` domain doesn't work on localhost. You can use `http://dub.localhost:8888` instead.

For example `http://dub.localhost:8888/<key>`
