### ISSUE TITLE
No option to delete workspace

### ISSUE THREAD

**Issue by bikrantjajware** [dubinc/dub#1036]
Hello 
When trying to delete account, it gived toast error to delete or transfer workspaces, however i dont option to delete workspace.
Tried searching in help docs but couldn't find it, im sure there is an option somewhere but its not easily navigable
Requesting for a fix for this issue, if possible i would also like to work on it, new to this repo :) 

<img width="1015" alt="image" src="https://github.com/dubinc/dub/assets/34072248/b9069063-d461-4651-9493-ac97388d7058">

**Comment by devkiran** [comment]
You can delete the workspace from the workspace settings. Click the `Setting` from the navigation on the top.

![image](https://github.com/dubinc/dub/assets/4593041/94237b74-48f7-4a5a-b055-818eb962d74f)
