### ISSUE TITLE
Workspaces Route is not working - https://app.dub.co/workspaces

### ISSUE THREAD

**Issue by chrisdadev13** [dubinc/dub#1065]
Application error: a client-side exception has occurred (see the browser console for more information).
<img width="1680" alt="Screenshot 2024-07-12 at 10 44 17 PM" src="https://github.com/user-attachments/assets/300d6b1d-778d-4322-851c-836912ad075d">

<img width="1679" alt="Screenshot 2024-07-12 at 10 44 33 PM" src="https://github.com/user-attachments/assets/58af5a40-7eb7-4f55-b480-0445ceb34c2c">

**Comment by steven-tey** [comment]
Great catch, thank you for reporting! Should be fixed now – this happens only for workspaces that don't have custom domains configured 👍
