### ISSUE TITLE
Issue with Google Calendar URL | ggl.link 

### ISSUE THREAD

**Issue by noz-yls** [dubinc/dub#1129]
Hola. Looks like a bug or missing feature. Please check. Thx

<img width="420" alt="image" src="https://github.com/user-attachments/assets/0ee7220c-7b75-4fe2-8ecd-b4aa2e1b50c9">

**Comment by steven-tey** [comment]
@noz-yls will fix this, thank you!

**Comment by steven-tey** [comment]
fixed by https://github.com/dubinc/dub/commit/847abbe290c7e2e1bd06e9fcef232bb472e22966
