### ISSUE TITLE
[BUG]: Unable to scan QR code

### ISSUE THREAD

**Issue by anav5704** [dubinc/dub#1137]
I am unable to scan the QR codes generated from links added to dub on the free tier. I encountered this issue today, QR codes worked fine a while back.

Noticeable difference: The QR codes that are generated now have a large padding area.

![Broken QR](https://github.com/user-attachments/assets/1444b792-80af-4047-89bd-1dfaa11e4ef2)

Workaround: Have to copy the QR code URL and paste it into a browser. This gives the working QR code.

![Working QR](https://github.com/user-attachments/assets/4ef00291-58f9-4192-8cc9-1013e368cf65)

**Comment by anav5704** [comment]
I just noticed that the QR code obtained using the workaround does not have the dub logo. However, I had previously made a QR code which did have the logo and did not have the padding and still worked.

**Comment by ay1x1912** [comment]
hey, @anav5704 I tried to generate a QR code, and it worked fine but  let us know if you are facing this problem again

**Comment by devkiran** [comment]
@anav5704 What device are you using to scan the QR codes?

**Comment by ay1x1912** [comment]
@anav5704  My one plus phone

**Comment by anav5704** [comment]
I tried scanning it with a Samsung A05s and Samsung S24. Some classmates of mine tried creating QR codes and it works fine for them. The ones I created were on Arc and Firefox.

**Comment by steven-tey** [comment]
This should be fixed now!
