### ISSUE TITLE
Customize OG image by platform (LinkedIn, X, etc.)

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1174]
LinkedIn made OG images small, so would be nice to show a different OG image for LinkedIn vs X

**Comment by bikrantjajware** [comment]
Is the issue for image resizing in social preview cards based on each platforms
ex- this is from Linkedin Spec (https://www.linkedin.com/help/linkedin/answer/a521928)
<img width="503" alt="image" src="https://github.com/user-attachments/assets/37604779-b0e5-4244-8fc0-0d3528bad350">

**Comment by saikatsardar01** [comment]
I would like to work on this issue but can you mark it as hacktoberfest ?

**Comment by steven-tey** [comment]
We're not going to support this for now, but maybe in the future!
