### ISSUE TITLE
Social Media Posting/Scheduling 

### ISSUE THREAD

**Issue by that-mike-bal** [dubinc/dub#1175]
I've been trying out a number of different social media scheduling tools lately and they all kind of suck. They are cumbersome, require too many steps, and over complicate the UI. When Buffer was relatively new, they had a simple queue and you could just set up how many posts a day you wanted. 

It would be great to have this inside Dub to keep content in circulation and keep channels active. 

I would want the ability to schedule a post from the Links screen in a simple modal. 
I would love for it to pull in the custom social media preview if it's available. 
It would be great if it had a reference for how I've shared that link in the past and AI could write new/unique to share it. 

If you explore this, I volunteer to help with the prompting on the AI front.

**Comment by steven-tey** [comment]
Thanks for the feature request! This is admittedly a bit out of our product focus at the moment so we probably won't be build this anytime soon. What we're planning to do though is to build integrations with platforms like Typefully (highly recommend them btw, I use it for all my social posts), Sprout Social, etc.
