### ISSUE TITLE
PrismaClient failed to initialize

### ISSUE THREAD

**Issue by zohaibafzal49** [dubinc/dub#1256]
⨯ Error [PrismaClientValidationError]: PrismaClient failed to initialize because it wasn't configured to run in this environment (Edge Runtime 
(Vercel Edge Functions, Vercel Edge Middleware, Next.js (Pages Router) Edge API Routes, Next.js (App Router) Edge Route Handlers or Next.js Middleware)).
[0] In order to run Prisma Client in an edge runtime, you will need to configure one of the following options:
[0] - Enable Driver Adapters: https://pris.ly/d/driver-adapters
[0] - Enable Accelerate: https://pris.ly/d/accelerate

Driver Adapter is already set here
generator client {
  provider        = "prisma-client-js"
  previewFeatures = [ "driverAdapters"]
}

**Comment by devkiran** [comment]
@zohaibafzal49 Please confirm you're using an edge-compatible database. Please follow the instructions [here](https://dub.co/docs/local-development#step-4-set-up-planetscale-mysql-database). Closing this now
