### ISSUE TITLE
Found a redirect issue in the user and workspace settings

### ISSUE THREAD

**Issue by mfts** [dubinc/dub#1259]
if you rename the workspace slug to `account`, then going to settings for that will bring you to `/account/settings` which is the same url as the user's settings and therefore you will never reach the workspace settings anymore.  

I know this isn't an issue per-se, but for example disallowing workspace slug from using the slug: "account" would solve this dilemma.

**Comment by steven-tey** [comment]
Thanks for reporting @mfts – we already disable the `account` slug :)
![CleanShot 2024-09-12 at 21 55 19](https://github.com/user-attachments/assets/09854d96-8e89-49cc-96cf-4026745b2650)
