### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by sanskar9415** [dubinc/dub#1260]
Redirect to figma tab not completely visible tabs should have been horizontly scrollable.

https://github.com/user-attachments/assets/bdf2c718-ec2e-480d-b66c-c1104963c874

**Comment by sanskar9415** [comment]
@devkiran let me know if it is a valid issue so that i can work on it.

**Comment by Neeraj-2525** [comment]
That Globe is the reason of all this slowness!

**Comment by steven-tey** [comment]
can't repro this – what device and browser are you on?

**Comment by sanskar9415** [comment]
I think the issue is resolved now i am closing this issue.

**Comment by sanskar9415** [comment]
but i recommend that for scrolling two fingers would be a general way to scroll this.
