### ISSUE TITLE
Claim domain button unresponsive in .link domain modal

### ISSUE THREAD

**Issue by artseabra** [dubinc/dub#1276]
# Claim domain button unresponsive in .link domain modal with React errors

## Description
When attempting to claim a new free .link domain, the "Claim domain" button in the modal is not responding to clicks. This issue is accompanied by React errors in the console, suggesting a problem with the React application.

## Steps to Reproduce
1. Navigate to https://app.dub.co/[company]/settings/domains
2. Click on "Claim new free .link domain"
3. Search for an available domain (e.g., "ifthis.link")
4. Receive the message: "ifthis.link is available. Claim your free domain before it's gone!"
5. Attempt to click the "Claim domain" button in the modal

## Expected Behavior
The "Claim domain" button should respond to clicks and initiate the domain claiming process.

## Actual Behavior
The "Claim domain" button does not respond to clicks. No action is taken when the button is clicked. Additionally, React errors are logged in the console.

## Environment
- Browser: Arc Browser
- Browser Version: 1.60.0 (53678)
- Chromium Engine Version: 128.0.6613.138
- Operating System: macOS Sonoma 14.4.1 (23E224)

## Console Errors

Uncaught Error: Minified React error #418; visit https://react.dev/errors/418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t7 (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:24817)
    at l9 (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:73176)
    at it (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:101959)
    at 01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97885
    at 01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97892
    at oY (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97997)
    at MessagePort.T (4476-6334cfe539f9dee3.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:84071)
01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1 

Uncaught Error: Minified React error #422; visit https://react.dev/errors/422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at 01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:64368
    at l1 (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:65719)
    at l9 (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:73671)
    at it (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:101959)
    at 01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97885
    at 01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97892
    at oY (01f950b4-f8389982da6c1625.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:97997)
    at MessagePort.T (4476-6334cfe539f9dee3.js?dpl=dpl_9muF8miffCtTWTyS55aA3apVkySm:1:84071)
domains:1 

Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

## Additional Information
- Frequency: This issue occurs consistently every time the process is attempted.
- The React errors suggest there might be issues with the React application's state management or rendering process.
- The third error indicates a problem with asynchronous operations, possibly related to the domain claiming process.

## Screenshot
![CleanShot 2024-09-17 at 15 59 35](https://github.com/user-attachments/assets/95149312-49da-4c04-8fb2-a71b54aa2d4e)

This screenshot shows the modal with the unresponsive "Claim domain" button.

**Comment by steven-tey** [comment]
@artseabra thanks for reporting this! Just seeing this issue but we already pushed a fix for this on the day itself – were you able to try it again and see if it's working again now?
