### ISSUE TITLE
Optimize disposable email domain validation using `SISMEMBER` instead of `SMEMBERS`

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1304]
Currently, the validation logic for checking if an email belongs to a disposable domain uses `SMEMBERS` to retrieve all the domains from the Redis set `disposableEmailDomains`, followed by an `includes()` check in the application code. This approach can be inefficient, especially as the size of the set grows, since both the Redis `SMEMBERS` command and the subsequent membership check have an overall time complexity of **O(N)**.

https://github.com/dubinc/dub/blob/628eb46bfe7012ac3f7d316e0584265b2d999c00/apps/web/lib/actions/create-user-account.ts#L33-L42

**Suggested Improvement:** To optimize this, you can directly use Redis’s `SISMEMBER` command, which has a constant time complexity **O(1)**, to check if the domain is part of the set without retrieving all the elements. 

**Proposed Code Change:**

```ts
const domain = email.split("@")[1];
const isDisposable = await redis.sismember("disposableEmailDomains", domain);

if (isDisposable) {
  throw new Error(
    "Disposable email addresses are not allowed. If you think this is a mistake, please contact us at support@dub.co",
  );
}
```

Another benefit the app can get from the proposed solution is **lower network overhead**: you will avoid fetching the entire set from Redis, reducing the amount of data transferred between Redis and the application.

**Links:**
- https://redis.io/docs/latest/commands/smembers/
- https://redis.io/docs/latest/commands/sismember/
- https://upstash.com/docs/redis/sdks/ts/commands/set/sismember#sismember

**Comment by steven-tey** [comment]
@unrenamed fantastic suggestion! Feel free to PR, will get this merged 🙏

**Comment by steven-tey** [comment]
@unrenamed added this to oss.gg btw, feel free to claim this issue and make the PR (instructions [here](https://oss.gg/))

**Comment by sudipb7** [comment]
I made a PR for it https://github.com/dubinc/dub/pull/1311

**Comment by unrenamed** [comment]
I guess the early bird really does get the worm... 😅

**Comment by sudipb7** [comment]
😅

**Comment by steven-tey** [comment]
Since this was @unrenamed's idea, I've closed @sudipb7's PR to give a chance for @unrenamed to make the changes instead.

@unrenamed do you want to comment `/assign` and get the issue assigned to you by OSS.gg, and create the PR instead?

**Comment by unrenamed** [comment]
Well, since you've already closed @sudipb7's PR, I guess I can only thank you and create the new one including @devkiran's review comments. Will do in a moment ✍️

**Comment by sudipb7** [comment]
Understood, no problem at all! Thanks for letting me know.
