### ISSUE TITLE
Incorrect link on side quests and challenges Notion doc

### ISSUE THREAD

**Issue by arunsathiya** [dubinc/dub#1313]
https://dubinc.notion.site/Dub-Hacktoberfest-Side-Quests-Challenges-1134c13445e780fd9ec9e6d292cd30c2

The link on the first bullet under **Dub: Code Contributions** takes me to [Formbricks'](https://github.com/formbricks/formbricks/labels/%F0%9F%95%B9%EF%B8%8F) while it should be [Dub's](https://github.com/dubinc/dub/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%95%B9%EF%B8%8F+oss.gg%22).

**Comment by steven-tey** [comment]
good catch, thank you!
