### ISSUE TITLE
Non-code contributions folder doesn't exist

### ISSUE THREAD

**Issue by arunsathiya** [dubinc/dub#1314]
On [this Notion doc](https://dubinc.notion.site/How-to-submit-a-non-code-contributions-via-GitHub-81166e8c948841d18209ac4c60280e60) (from [Dub - Hacktoberfest Side Quests & Challenges](https://dubinc.notion.site/Dub-Hacktoberfest-Side-Quests-Challenges-1134c13445e780fd9ec9e6d292cd30c2)), it sounds like there should be a `oss.gg` folder, but I don't see it for Dub?

**Comment by steven-tey** [comment]
fixed! thanks!

**Comment by arunsathiya** [comment]
I am not sure I see the folder yet. Could you clarify where it is supposed to be? [I am expecting it to be somewhere like on Formbricks' project](https://github.com/formbricks/formbricks/tree/main/oss-gg).

Also makes me wonder if this approach is good for only short-term events. The non-code contributions could be tracked differently, I feel, but I don't have a strong suggestion to the oss.gg team(s) just yet.
