### ISSUE TITLE
Improve not found page 

### ISSUE THREAD

**Issue by RajuGangitla** [dubinc/dub#1325]
if you hit a not found page , the page looks like below 

we can improve and  style it better 

![404_ This page could not be found  - Google Chrome 05-10-2024 13_31_34](https://github.com/user-attachments/assets/c8254a2d-23b5-4c77-9e63-c23cc4e88ff6)

@steven-tey

**Comment by saikatsardar01** [comment]
I would like to work. But can u=you mark it as hactoberfest?
