### ISSUE TITLE
Possible promise race condition on sending OTP   

### ISSUE THREAD

**Issue by mfts** [dubinc/dub#1327]
As I'm currently rebuilding email verification process on my end, I had to check out how Dub is solving it. 

I came across this part of the `send-otp` function and it may be possible that the `deleteMany` mutation executes after the `create` mutation and therefore deletes the `code` you just sent to your user. 

https://github.com/dubinc/dub/blob/0a52e984ed9c43575d09fecb2c87df5d7c2b5543/apps/web/lib/actions/send-otp.ts#L50-L65

At least when I tried to implement it similarly using the `Promise.all` with deleteMany and create, that's exactly what happened.

**Comment by steven-tey** [comment]
Great catch, thank you! Fixed it [here](https://github.com/dubinc/dub/commit/aa1ae3309dc101b8121a2621b4ae41f526edf8bb)
