### ISSUE TITLE
Allow users to "reactivate" their Dub subscription

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1331]
Currently, users who have canceled their Dub subscription in the past have no way to "reactivate" their subscription without creating an entirely new subscription.

This should be a super simple fix – in [this route handler](https://github.com/dubinc/dub/blob/main/apps/web/app/api/workspaces/%5BidOrSlug%5D/billing/upgrade/route.ts), we need to add an extra condition for when a user has a `stripeId` but no active `subscription`, and create the Stripe checkout session accordingly instead.

**Comment by RajuGangitla** [comment]
@steven-tey dont we have any discord channel

**Comment by Pratham271** [comment]
if available /assign me

**Comment by sudipb7** [comment]
I've implemented it locally. If available you can assign me :)

**Comment by RajuGangitla** [comment]
@sudipb7 im already working on it

**Comment by sudipb7** [comment]
@RajuGangitla No problem. That's why I asked before creating a PR

**Comment by steven-tey** [comment]
@RajuGangitla we don't have a Discord, but feel free to ping me on [Twitter](https://twitter.com/steventey) with any questions!
