### ISSUE TITLE
Use OAuth login flow for Dub CLI (`dub-cli`)

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1334]
- Docs: https://d.to/oauth
- Potential guide: https://thecodebarbarian.com/oauth-in-nodejs-cli-apps.html

**Comment by sujjeee** [comment]
hey @RajuGangitla already worked on it 
![Screenshot 2024-10-07 132935](https://github.com/user-attachments/assets/b8380874-c7a7-4ee9-826e-3a8169981830)

**Comment by RajuGangitla** [comment]
@sujjeee how you already start working on it issue just created right 
or are you working on this previously ?

**Comment by sujjeee** [comment]
> @sujjeee how you already start working on it issue just created right or are you working on this previously ?

![image](https://github.com/user-attachments/assets/a71c68b1-ff8e-496f-934b-f822bcd6cba1)
@RajuGangitla  yessss

**Comment by RajuGangitla** [comment]
@sujjeee then its yours

**Comment by sujjeee** [comment]
reallyyy thanks @RajuGangitla btw, you're killing it in other repos too. saw your contributions!!

**Comment by RajuGangitla** [comment]
@sujjeee if you dont mind , would love to connect with you

**Comment by sujjeee** [comment]
@RajuGangitla feel free to dm me on X

**Comment by devkiran** [comment]
@sujjeee Let us know if you have any questions. I'm curious to see our Standard OAuth flow can be used for CLI. Device Authorization Grant is the most standard one with CLI. Looking forward to your thoughts.

**Comment by sujjeee** [comment]
@devkiran sure will let you know :)
