### ISSUE TITLE
Solved 3 Side Quests

### ISSUE THREAD

**Issue by RajuGangitla** [dubinc/dub#1338]
1. Follow on X (50 points)

twitter profile link ---> https://x.com/LovelyDavid8185

![image](https://github.com/user-attachments/assets/e9314282-cbe9-4c00-b7cd-0c03054a92d2)

2. Follow on LinkedIn (50 points)

linkedIn profile Link   ---> https://www.linkedin.com/in/raju-gangitla-096717253/

![image](https://github.com/user-attachments/assets/60e8d236-5c61-475b-8d52-3a2d91f8de84)

3.starry-eyed Supporter (150 Points): 

their usernames 
https://github.com/hari4742
https://github.com/Sara2706
https://github.com/VKaushik017
https://github.com/Suri-Jayraj
https://github.com/JoshanSai

![image](https://github.com/user-attachments/assets/22938d4e-8564-425e-acca-772aef3d5d0a)

![image](https://github.com/user-attachments/assets/58590a06-3f6b-4ae7-bb22-b71bd1c49ca1)

![image](https://github.com/user-attachments/assets/85a4fef5-c386-410a-9d18-b4cf61caf9d4)

![image](https://github.com/user-attachments/assets/9c0d3fcc-658f-426d-8bc9-0bf2343b9151)

![image](https://github.com/user-attachments/assets/ce554be6-abb5-4187-9a83-9462db2036e4)

**Comment by naaa760** [comment]
> [ENG-616 Solved 3 Side Quests](https://linear.app/dubinc/issue/ENG-616/solved-3-side-quests)

I would like to solve this 3 slide quests!
Thankyou!

**Comment by steven-tey** [comment]
@RajuGangitla They are, thank you!
