### ISSUE TITLE
oss.gg: Solve 3 side quests

### ISSUE THREAD

**Issue by Ionfinisher** [dubinc/dub#1344]
Follow dub.co on linkedIn:  50 points

<img width="1177" alt="Screen Shot 2024-10-10 at 02 48 00" src="https://github.com/user-attachments/assets/5df49a7e-9a80-42a3-a8f8-761444e2fc33">

Follow dub.co on X (Twitter): 50 points

<img width="904" alt="Screen Shot 2024-10-10 at 02 50 57" src="https://github.com/user-attachments/assets/ac9ad2c4-ec24-4709-9e71-772c74ddcd37">

Design a billboard ad for dub.co : 300 points

<img width="548" alt="dub_billboard" src="https://github.com/user-attachments/assets/3f8902e5-f2c0-4ded-a760-2ed0096d10a9">

**Comment by steven-tey** [comment]
Thank you! That billboard ad is amazing 😍
