### ISSUE TITLE
Improvement in UI of Landing Page

### ISSUE THREAD

**Issue by Harshit-Keshari** [dubinc/dub#1362]
![image](https://github.com/user-attachments/assets/5daae475-35fa-49b4-9840-6873a0793e14)

On this section some logos does not has effects on hover.

**Comment by itsmanasdash** [comment]
I checked all are working good only vercel ,replicate , attio and cal.com don't have effects because they don't have a colored logo . Replicate logo have white version but with red background .

**Comment by idealgeek007** [comment]
> I checked all are working good only vercel ,replicate , attio and cal.com don't have effects because they don't have a colored logo . Replicate logo have white version but with red background .

Lol the repo doesn't have the landing page code

**Comment by itsmanasdash** [comment]
> > I checked all are working good only vercel ,replicate , attio and cal.com don't have effects because they don't have a colored logo . Replicate logo have white version but with red background .
> 
> Lol the repo doesn't have the landing page code

Sorry i can't get you . I checked on the website

**Comment by steven-tey** [comment]
yup, what @itsmanasdash said ☝️
