### ISSUE TITLE
Follow Dub on Twitter oss.gg

### ISSUE THREAD

**Issue by SoumyadeepOSD** [dubinc/dub#1368]
https://twitter.com/SoumyadeepDasB6 followed https://twitter.com/dubdotco

![Screenshot 2024-10-11 065937](https://github.com/user-attachments/assets/60bcabba-d990-4dd4-88a8-c231fdff3fb7)

**Comment by sharimkhan01** [comment]
[sharimkhan01](https://github.com/sharimkhan01) followed [Dub](https://x.com/dubdotco)

<img width="891" alt="Screenshot 2024-10-11 at 9 35 53 AM" src="https://github.com/user-attachments/assets/15a1b3f5-6d8d-43f8-a694-cf24920a197c">
