### ISSUE TITLE
Follow Dub on LinkedIn oss.gg

### ISSUE THREAD

**Issue by SoumyadeepOSD** [dubinc/dub#1369]
[Soumyadeep](https://www.linkedin.com/in/soumyadeep-das-bhowmick-01a882234) followed [Dub](https://www.linkedin.com/company/dubinc/posts/?feedView=all)  

![Screenshot 2024-10-11 071137](https://github.com/user-attachments/assets/703ffcf0-511c-414d-8f15-c8662866f6b2)

**Comment by devXpraAddy** [comment]
[devXpraAddy](https://www.linkedin.com/in/devxadityaprajapati/)  followed [Dub](https://www.linkedin.com/company/dubinc/
)

<img width="575" alt="image" src="https://github.com/user-attachments/assets/0f18c435-d896-44f4-b5b5-e6714c74a99b">

**Comment by sharimkhan01** [comment]
[https://github.com/sharimkhan01](url) followed [https://www.linkedin.com/company/dubinc/](url)
<img width="903" alt="Screenshot 2024-10-11 at 9 39 20 AM" src="https://github.com/user-attachments/assets/f7537b0d-87b0-452a-a01c-7e7cc2ca5206">
