### ISSUE TITLE
"UI Bug: Unable to Click All Buttons in the Display Properties Section"

### ISSUE THREAD

**Issue by naaa760** [dubinc/dub#1370]
**Issue Description:**

_When attempting to interact with the buttons in the "Display Properties" section of the settings menu, some buttons are not clickable or accessible due to layout issues. This prevents users from selecting all display properties to set them as the default._

- Area: Display Properties in settings.

- Issue: Two buttons remain unclickable.

- Expected: All buttons should be clickable.

- Observed: Some buttons stay unselected.

Possible Causes:

- Overflow or fixed-size container.

- Z-index or layering issues.

- Responsive design flaws.

- JavaScript click event issues.

https://drive.google.com/file/d/12i1MToVSA7hOPDNQhFsAwsGohMxDIHdC/view?usp=drivesdk

![Screenshot from 2024-10-11 08-42-47](https://github.com/user-attachments/assets/b5400b1c-642b-435a-b6bf-3506863021af)

**Comment by amith-webdeveloper** [comment]
i think it is click event issue

**Comment by dineshsutihar** [comment]
I think this is done intentionally to maintain a clean UI: they are replacing `Short link` with `Title` and `Destination URL` with `Description`.

**Comment by steven-tey** [comment]
Yup, what @dineshsutihar said ☝️
