### ISSUE TITLE
[🕹️] Followed Dub on LinkedIn

### ISSUE THREAD

**Issue by dineshsutihar** [dubinc/dub#1376]
[🕹️] Followed [Dub on LinkedIn](https://www.linkedin.com/company/dubinc/) (50 Points)
[@dineshsutihar](https://www.linkedin.com/in/dineshsutihar/)

![Screenshot](https://github.com/user-attachments/assets/c765c2c5-401e-4cc5-8ac9-02fd4ce7b9a8)

**Comment by Anky9972** [comment]
![image](https://github.com/user-attachments/assets/ce274d9a-e4fd-45df-b6ee-aceeafa560e1)
