### ISSUE TITLE
[🕹️] Follow Dub on Twitter

### ISSUE THREAD

**Issue by Khaan25** [dubinc/dub#1378]
[🕹️] Followed [Dub on Twitter](https://twitter.com/dubdotco)

50 Points

[@zia_webdev](https://x.com/zia_webdev)

![image](https://github.com/user-attachments/assets/b61c440b-ffed-4ce9-9758-2e3fa0a2298c)

**Comment by SrinivasReddy78** [comment]
![image](https://github.com/user-attachments/assets/756b85f1-0599-4cd6-a604-4e1f797f5493)
