### ISSUE TITLE
[🕹️] Follow Dub on Twitter

### ISSUE THREAD

**Issue by ishwarthecodddr** [dubinc/dub#1385]
Here's the proof : 
![image](https://github.com/user-attachments/assets/ad6ce022-c2e4-49fd-bc52-98ed3f75c9b9)

**Comment by rxhul18** [comment]
Here's the proof to Follow Dub on Twitter :
<img width="984" alt="image" src="https://github.com/user-attachments/assets/1a8493fa-e970-4b76-b483-9739705f2da8">
