### ISSUE TITLE
[🕹️] Follow Dub on Twitter

### ISSUE THREAD

**Issue by GrowthCoder7** [dubinc/dub#1390]
![image](https://github.com/user-attachments/assets/ba665f78-39d6-4371-bca8-c6fe315255db)

Prince Kumar

@PrinceK1407

**Comment by konarksharma2001** [comment]
![Screenshot 2024-10-11 175607](https://github.com/user-attachments/assets/cc4b09af-73ab-4cc5-908f-e726ee7db80e)

Konark Sharma

@Konark_2001
