### ISSUE TITLE
Follow Dub X (Twitter) Account

### ISSUE THREAD

**Issue by Nisarg-Sha** [dubinc/dub#1396]
<img width="1512" alt="Screenshot 2024-10-11 at 7 19 15 PM" src="https://github.com/user-attachments/assets/a856acb8-d67c-4a01-b813-7f02b55c63c5">

**Comment by SrinivasReddy78** [comment]
![image](https://github.com/user-attachments/assets/c15ede9e-3bd1-41dc-b979-4ef970206f7f)
