### ISSUE TITLE
I found a bug in the dashboard where the preview width is too small, causing letters like 'g' and 'q' not to show completely

### ISSUE THREAD

**Issue by avishek999** [dubinc/dub#1399]
![Screenshot (54)](https://github.com/user-attachments/assets/00e4d5f9-67ac-45e0-a0e7-37cdf4884a5a)

In the dashboard, I found a bug that causes letters like 'g' and 'q' not to display completely.

**Comment by avishek999** [comment]
assign me this task i can fix it

**Comment by steven-tey** [comment]
Can't repro, which browser is this?

**Comment by avishek999** [comment]
chrome
