### ISSUE TITLE
Dub Sidequest : Follow on Twitter and Linkedin 

### ISSUE THREAD

**Issue by mukulpythondev** [dubinc/dub#1413]
Proof: 
### Linkedin 
![Screenshot from 2024-10-12 09-10-22](https://github.com/user-attachments/assets/ce1f9734-8549-48be-9f71-aed62cead89e)

### Twitter 
![dubfollowing](https://github.com/user-attachments/assets/9ac76c0c-125d-4fe8-bbc8-1b12068ab241)

**Comment by Xeroworld** [comment]
Linkedin
<img width="958" alt="Screenshot 2024-10-12 120246" src="https://github.com/user-attachments/assets/24e59814-c7d4-4265-9bf3-70769a9daa67">
Twitter
<img width="852" alt="image" src="https://github.com/user-attachments/assets/1f401c50-08d7-4466-9f3e-8277e0f16746">
