### ISSUE TITLE
Horizontal scroll bar at the bottom of the sign up and log in pages

### ISSUE THREAD

**Issue by Kiran-F** [dubinc/dub#1427]
There's an unexpected horizontal scroll bar at the bottom of sign-up and log-in pages.
Consider this issue.
![Screenshot (641)](https://github.com/user-attachments/assets/d0c83dbc-61ee-439d-9393-9e1ddcd493e4)
oss.gg points required for raising issue.

**Comment by steven-tey** [comment]
Great catch! Assigned to oss.gg – feel free to PR!

**Comment by Kiran-F** [comment]
Also add the hacktoberfest-accepted label to this issue

**Comment by Kiran-F** [comment]
@steven-tey I've created a PR for this issue. Please check it out.

**Comment by Kiran-F** [comment]
@steven-tey I've created a PR for this issue. Please check it out.

**Comment by harjasae2001** [comment]
when will the next person get to work on this issue.
