### ISSUE TITLE
[🕹️]  Background image gets cropped when Opening the Help Center in Mobile Responsive

### ISSUE THREAD

**Issue by aryany9** [dubinc/dub#1428]
![image](https://github.com/user-attachments/assets/2340ab66-6737-41fe-a3de-0a99454ec5d4)

Steps to Produce: 
1) Open the landing page. https://app.dub.co
2) Change to Mobile View
3) Open the help center (? icon)

Points: 150?

**Comment by RaghavMangla** [comment]
pls assign this to me

**Comment by steven-tey** [comment]
Great catch! Assigned to oss.gg – feel free to PR!

**Comment by aryany9** [comment]
> Great catch! Assigned to oss.gg – feel free to PR!

Hi Steven, Did not get the points of bug bounty side quest. When created the issue. As the labels were not there. Can you help?

**Comment by BadriVishalPadhy** [comment]
hey @tomarxd @steven-tey  if u are not able please can u assign this issue to me

**Comment by aryany9** [comment]
@steven-tey /reward

**Comment by aryany9** [comment]
@steven-tey waiting for the bug bounty reward. Thanks

**Comment by pnk-ltoc-892** [comment]
Not seeing the issue on my side

**Comment by pnk-ltoc-892** [comment]
elborate the issue and correct steps

**Comment by steven-tey** [comment]
@anjaliydv304 are you still working on this?
