### ISSUE TITLE
When the user cancels the Google login, they should be redirected back to the original login

### ISSUE THREAD

**Issue by jagdishjadeja** [dubinc/dub#1429]
Issue: Incorrect Redirect After Cancelling Google Login

Steps to Reproduce:

	1.	Navigate to https://app.dub.co/login
	2.	Click on “Continue with Google” – this opens the Google account selection list.
	3.	Select an account – it prompts for permission to log in with Google on dub.co.
	4.	Click on “Cancel” at the permission screen.
	5.	The app redirects to an API route:
https://app.dub.co/api/auth/signin?error=Callback
	6.	Expected Behavior:
	•	It should redirect to https://app.dub.co/login with an error message like:
"Action/operation cancelled"

**Comment by bandhan-majumder** [comment]
are you working on this? Else I would like to work on this.

**Comment by steven-tey** [comment]
Good catch! Assigned this to oss.gg – feel free to fix it!
