### ISSUE TITLE
SideQuest: Follow Dub on Twitter (50 Points)

### ISSUE THREAD

**Issue by A10-g** [dubinc/dub#1442]
![image](https://github.com/user-attachments/assets/0964a3d8-63c3-4677-9833-a063730fb522)

**Comment by riyanrathore26** [comment]
TASK COMPLETED
<img width="609" alt="twitter" src="https://github.com/user-attachments/assets/66b22121-cb7c-49b4-ac15-77fae2f74c38">

**Comment by sr1936** [comment]
![Screenshot 2024-10-13 123108](https://github.com/user-attachments/assets/25ec60c6-a505-4a93-825c-4c1243075c5a)
  complete  task #1442
