### ISSUE TITLE
Bug Hunter: Page is not redirecting to homepage after deleting the workspace

### ISSUE THREAD

**Issue by Sa1-Codes** [dubinc/dub#1448]
after creating a workspace, when we delete the workspace after the successful deletion it is showing 404 page. It is not redirecting to the homepage , even after clicking the "Go back home" button. It is also not redirecting to home when changing the url. It stays on the same 404 page.

what to fix (according to me):
after click the "Go back home" , it should redirect user to the home page.

Proof:

https://github.com/user-attachments/assets/0be63cda-c8f2-43b8-a971-9967ab332f9c

points: 150

**Comment by samarsrivastav** [comment]
I would love to work on this issue
