### ISSUE TITLE
[🕹️] ossgg: Follow Dub on Twitter

### ISSUE THREAD

**Issue by EzyHow** [dubinc/dub#1458]
Followed Dub on Twitter

**ossgg:** 50 Points

**Proof:**
![image](https://github.com/user-attachments/assets/02a02f1e-b27e-462d-814b-70598b142dfd)

**Comment by shivam-911** [comment]
Followed Dub on Twitter

ossgg: 50 Points

Proof:
![Screenshot 2024-10-14 121229](https://github.com/user-attachments/assets/10346511-b441-4648-8462-49564eb34f77)
