### ISSUE TITLE
[🕹️] ossgg: Follow Dub's LinkedIn Page (50 Points):

### ISSUE THREAD

**Issue by soummyaanon** [dubinc/dub#1464]
**I followed Dubs [Linkedin Page](https://www.linkedin.com/company/dubinc/posts/?feedView=all) & my Linkedin Handel is [Click here](https://www.linkedin.com/in/soumyapanda12/)**

**Points**
**50**

### **Provide proof that you've completed the task**
![Screenshot 2024-10-11 at 11 30 14 AM](https://github.com/user-attachments/assets/8570c768-5b70-4879-b316-0432361fe0fd)

**Comment by shivam-911** [comment]
Sidequest: Follow [Dub on Twitter](https://twitter.com/dubdotco) (50 Points): My Linkedin Handle:https://www.linkedin.com/in/shivam-sharma-214a8431b/
Proof:
![Screenshot 2024-10-14 122141](https://github.com/user-attachments/assets/b033cc3e-b646-4a30-9c4b-899940407679)
