### ISSUE TITLE
Adding a moving carousel rather than static cards.

### ISSUE THREAD

**Issue by Atharva-3000** [dubinc/dub#1479]
![image](https://github.com/user-attachments/assets/124b3f2d-7bb4-47bc-bd53-ce8907c2d456)

Will probably require access to the LP repo.

Rather than having cards, we can have a moving carousel type of thing which can cover all other things like chatGPT, amazon etc.

**Comment by steven-tey** [comment]
appreciate the suggestion here, but this is by design! might change this in the future though!
