### ISSUE TITLE
Add custom messages for NextAuth errors

### ISSUE THREAD

**Issue by TWilson023** [dubinc/dub#1481]
Errors from NextAuth currently result in pretty ambiguous messages like this one:

![Screenshot 2024-10-14 at 3 23 34 PM](https://github.com/user-attachments/assets/fec2e526-a2e6-4e30-a09b-70ca94e5806a)

We should add nicer messages for these errors:
* `Callback`
* `OAuthSignin`
* `OAuthCallback`

...plus a generic catch-all error message for the rest.

Possible errors: https://next-auth.js.org/configuration/pages#sign-in-page

See [apps/web/app/app.dub.co/(auth)/login/form.tsx:90-93](https://github.com/dubinc/dub/blob/f3f8e2715fc2b9fbd9292741b36443963f389815/apps/web/app/app.dub.co/(auth)/login/form.tsx#L90-L93)

**Comment by RajuGangitla** [comment]
@TWilson023 do i need to add the conditions for the error message in this file 

https://github.com/dubinc/dub/blob/f3f8e2715fc2b9fbd9292741b36443963f389815/apps/web/app/app.dub.co/(auth)/login/form.tsx#L90-L93

**Comment by TWilson023** [comment]
@RajuGangitla yes I believe so, unless you have a better idea!

**Comment by RajuGangitla** [comment]
@TWilson023 i will do it in the login form only
