### ISSUE TITLE
tb push error "The pipe has columns ['metadata'] not found in the destination Data Source"

### ISSUE THREAD

**Issue by nokoa77** [dubinc/dub#1483]
Hi all,

I followed the self-hosting guide, and run into this error when typing "tb push" : 

Error: 
** Failed running ./pipes/dub_lead_events_pipe.pipe: 
** Invalid results, read description below to fix the error: Cannot materialize node: The pipe has columns ['metadata'] not found in the destination Data Source.. If you want to try to force override the Materialized View, please use the `--override-datasource` flag

I started again another time from scratch, but I again found this error at the same step.

could you help me please ? 

thanks

Bruno

**Comment by nokoa77** [comment]
Hi @steven-tey , for the previous similar errors (eg. : issue #958 ) you seemed to have the answer, would you accept to "do the same magic" here ? (ie update Tinybird schema/pipes).
Or maybe could you please tell me if my situation is different? Thank you, Bruno

**Comment by sp9324** [comment]
> Hi all,
> 
> I followed the self-hosting guide, and run into this error when typing "tb push" :
> 
> Error: ** Failed running ./pipes/dub_lead_events_pipe.pipe: ** Invalid results, read description below to fix the error: Cannot materialize node: The pipe has columns ['metadata'] not found in the destination Data Source.. If you want to try to force override the Materialized View, please use the `--override-datasource` flag
> 
> I started again another time from scratch, but I again found this error at the same step.
> 
> could you help me please ?
> 
> thanks
> 
> Bruno

Hey, I'm facing the same exact issue. Did you find a solution?

**Comment by nokoa77** [comment]
Hi, no, I'm still stuck at this step. Apparently, an action is needed from the team (cf my previous message) to adapt to new Tinybird schema. So i'm waiting :)

**Comment by sp9324** [comment]
> Hi, no, I'm still stuck at this step. Apparently, an action is needed from the team (cf my previous message) to adapt to new Tinybird schema. So i'm waiting :)

Oh, okay. Thanks :)
