### ISSUE TITLE
Possible Security Issue

### ISSUE THREAD

**Issue by MathysB21** [dubinc/dub#1532]
Hi All, I'm unsure if this is a security issue as I'm still quite new to development and cybersecurity. However, I scoured through the repo to learn more about large-scale development and found an IP along with coordinates. 

Did you mean to add this here? Here's the path: packages/utils/src/constants/localhost.ts

**Comment by steven-tey** [comment]
This is a dummy IP address / coordinate values for localhost testing, not a security issue 👍
