### ISSUE TITLE
San Francisco Billboard Ad

### ISSUE THREAD

**Issue by rajeevDewangan** [dubinc/dub#1538]
![Screenshot 2024-10-17 135256](https://github.com/user-attachments/assets/b7e72f2c-457a-4ee7-8987-a87d4dd92417)
link to tweet : https://x.com/rajeevdew/status/1846829032698270065
Ad
![dubBanner](https://github.com/user-attachments/assets/cffb49fe-b753-49c1-ab61-308ee278a046)
SF Billboard Ad
![dubBillboard](https://github.com/user-attachments/assets/ada8e210-b568-409b-902a-59ea1c3165b6)
Points - 200

**Comment by steven-tey** [comment]
billboard ad is just a copy paste of our main thumbnail – reducing points from 200 to 100
