### ISSUE TITLE
[🕹️ oss.gg Hackathon] Docs: Updated Hyperlinks 

### ISSUE THREAD

**Issue by Atharva-3000** [dubinc/dub#1561]
### Updated hyperlinks to the Dub docs, here is the link to the PR:

https://github.com/dubinc/docs/pull/97

**Ps: You accidentally awarded someone with 3000 points instead of 300 for updating a doc in one of the closed issues** 🥹🥹

**Comment by steven-tey** [comment]
Thank you so much!
