### ISSUE TITLE
The carousel is not auto playing

### ISSUE THREAD

**Issue by garvitj2003** [dubinc/dub#1570]
Here's a detailed issue message you can raise on the GitHub repo for Dub.co regarding the carousel animation problem:

Issue: Carousel is Not Animating Automatically
Description:
I noticed that the carousel component does not animate automatically as expected. Ideally, the carousel should slide from left to right (or right to left) continuously without user interaction, but it remains static unless manually navigated.
![image](https://github.com/user-attachments/assets/8e9e8d2a-cbfc-4df0-b589-ed22a4bb986b)

Steps to Reproduce:
Navigate to the page containing the carousel.
Wait for the carousel to auto-play.
Observe that there is no automatic sliding or animation taking place.
Expected Behavior:
The carousel should automatically animate, moving through the slides from left to right or right to left without requiring manual interaction.

Actual Behavior:
The carousel remains static, and slides do not change unless manually navigated by the user.

**Comment by devkiran** [comment]
Duplicate https://github.com/dubinc/dub/issues/1479
