### ISSUE TITLE
[🕹️] QR Code color Picker doesn't work !

### ISSUE THREAD

**Issue by soamn** [dubinc/dub#1571]
The Color Picker in QR code generator Doesn't work .
In Large devices It completely crashes the page .( Its working when I use in full screen)
In small devices it does not work, doesn't do anything.

Steps to Recreate ->When In dub.co Go to Links Section

1. Create Link ( C ).
2. Enter Any Destination URL.
3. Choose any Short Link.
4. Edit the QR Code Section.
5. Head to QR code color Selector ( color Picker ) . drag to any color ->
App crashes on large screens && doesn't change color for small screen

https://github.com/user-attachments/assets/5e2e5545-ff99-436b-9306-ffc2abee4982

**Comment by steven-tey** [comment]
Thank you for the bug report!
