### ISSUE TITLE
🕹️ Follow Dub's LinkedIn account (50 Points) completed side-quest

### ISSUE THREAD

**Issue by adilkadivala** [dubinc/dub#1587]
i have followed Dub's account on LinkedIn

profile link

https://www.linkedin.com/in/adilkadival

here it is

![dublinkedin](https://github.com/user-attachments/assets/80b2f8e8-4ce8-40d6-90ec-2f9060f7aab7)

**Comment by pranavsinghpatil** [comment]
![Screenshot 2024-10-21 151352](https://github.com/user-attachments/assets/f056b609-2fdb-46b4-9a0e-ba28b9d66897)

I have followed dub linkedIN page

my profile link:-
www.linkedin.com/in/pranavsinghpatil
