### ISSUE TITLE
Follow on X and billibord

### ISSUE THREAD

**Issue by AshishViradiya153** [dubinc/dub#1605]
Ashish Viradiya

Total: 250points 

50points
<img width="534" alt="Screenshot 2024-10-22 at 3 26 28 PM" src="https://github.com/user-attachments/assets/6bdb0dc2-e877-4ab5-98aa-ee65056decb0">

200Points
![image](https://github.com/user-attachments/assets/1a76b82c-5123-42cd-bb4f-0e930d401871)

**Comment by steven-tey** [comment]
billboard is clearly generated with AI
