### ISSUE TITLE
[🕹️] Quest Submission : San Francisco Billboard Ad

### ISSUE THREAD

**Issue by sateshcharan** [dubinc/dub#1606]
![billboard dub](https://github.com/user-attachments/assets/898b215f-12db-4790-a957-6cfb967b64ce)

points

200

**Comment by steven-tey** [comment]
this looks realy good, you should tweet about it!

**Comment by sateshcharan** [comment]
thank you; tweet's @ https://x.com/sateshcharans/status/1848783741814284640
