### ISSUE TITLE
UI Breaks on `Add New API Key` Drawer with `Restricted` Permissions on Mobile

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1609]
### Issue Summary

When accessing the `Settings > API Keys` page on mobile, opening the `Add new API Key` drawer and selecting the `Restricted` permissions option causes UI issues. The `Create API key` button becomes unclickable, and the animated list of restricted permissions appears incomplete, as it is cut off at the bottom. This issue prevents users from completing the process of adding a new API key with restricted permissions.

### Steps to Reproduce

1. Open the application on a mobile device.
2. Navigate to `Settings > API Keys`.
3. Click on the `Create` button to open the drawer.
4. Select the `Restricted` permissions option from the available options.
5. Try to scroll through the animated list of restricted permissions.

### Expected behavior

1. The UI should display the full list of restricted permissions without being cut off at the bottom.
2. The `Create API Key` button should remain clickable and functional, allowing the user to proceed with adding a new API key.

### Screenshots/Videos

https://github.com/user-attachments/assets/2d389a85-ca4a-4500-82e9-5b30dcc6a019

### Version info

Tested on both:
1. iPhone 8+ iOS 16.7.10
2. Brave 1.71.114 Chromium: 130.0.6723.58 (Official Build) (arm64)

The video was recorded using Brave browser. The issue is the same on iOS, although looks just a bit different (the scroll does not work at all, i.e. there is no empty white space at the bottom)

**Comment by steven-tey** [comment]
Good find!

**Comment by aritradevelops** [comment]
@steven-tey please have a look at my PR and suggest if any further changes is needed! Thanks!

**Comment by unrenamed** [comment]
@aritradevelops I see you've submitted a PR for this bug. However, this bug was assigned to me, and **I'm actively working on a fix**. According to the project guidelines, I still have 48 hours to submit my PR. In the future, it would be great to respect assignments and give others the opportunity to complete their tasks.

**Comment by aritradevelops** [comment]
Hey @unrenamed I'm really sorry 🙏🏽, I was unaware that `oss.gg guidelines` does not allow PR for assigned open issues.I thought it's a competition so whoever finds the solution first can raise a PR.  I just found a working solution within an hour therefore I have raised a PR for the same. So I will wait for your 48 hours to end if you find a better solution please proceed. I have no issues. We're both trying to win here, this often happen in case of bug bounties, it's not like I'm not respecting your assignment. None the less sorry again, Pal.

**Comment by steven-tey** [comment]
Appreciate your PR @aritradevelops but yes, this issue was assigned to @unrenamed so I'll default to him to create a PR within 48 hours  before reviewing other submissions 🙏

**Comment by sour2001** [comment]
assign
