### ISSUE TITLE
[🛠️ Improvement]: Move `navigator.clipboard` usages to `useCopyToClipboard` hook

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1633]
## Overview
Currently, multiple instances of `navigator.clipboard.writeText()` are directly used across different components for copying text to the clipboard. This pattern leads to code duplication and could be improved by consolidating the functionality into a reusable `useCopyToClipboard` hook. 

## Proposal
I suggest creating a custom React hook named `useCopyToClipboard` to handle all clipboard operations. This hook would encapsulate the logic for copying not just strings but also objects implementing the [ClipboardItem interface](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem). This means it'd be capable of copying images, such as QR codes, to the buffer too. 

## Benefits
- Centralizing clipboard logic in a single hook ensures we avoid repeating the same `navigator.clipboard` calls across components.
- Any changes or bug fixes to clipboard functionality can be made in one place, reducing the risk of missing updates across the app.

## Example usage

```typescript
import { useCopyToClipboard } from '@/hooks/useCopyToClipboard';

const ExampleComponent = () => {
    const [copied, copyToClipboard] = useCopyToClipboard(3000); // timeout in ms; determines how long the "copied" state stays true before reverting to false after copying to the clipboard.
    
    const handleCopy = () => {
        copyToClipboard('Some text to copy');
    };

    return (
        <button onClick={handleCopy}>
            {copied ? 'Copied!' : 'Copy'}
        </button>
    );
};

```

## Screenshots
<img width="533" alt="image" src="https://github.com/user-attachments/assets/03c4cddb-f6c9-4f9e-9d20-4a241b705b4b">

**Comment by steven-tey** [comment]
Great idea, let's do it!
