### ISSUE TITLE
User can create a UTM template with only whitespace characters in the name and UTM parameters

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1647]
### Issue Summary

Users are currently able to create UTM templates where the name and UTM parameters consist only of whitespace characters. This results in templates that appear blank, which can lead to confusion when reviewing or editing them.

### Steps to Reproduce

1. Navigate to the UTM template creation page: [https://app.dub.co/\<your-workspace\>/settings/library/tags](https://app.dub.co/<your-workspace>/settings/library/tags)
2. Enter only whitespace characters in the "Name" field.
3. Enter only whitespace characters in one or more of the UTM parameter fields (e.g., utm_source, utm_medium, etc.).
4. Save the template.

### Expected behavior

Following Dub's design convention, creating a template with only whitespace characters should be prevented. This may include showing an error message or an error toast. The assignee should clarify this with the core team before they start coding. 

### Reproduction / Screenshots

https://github.com/user-attachments/assets/f0143359-0cdf-4763-a7ec-1133e9ecd151

<img width="300" alt="Screenshot 2024-10-25 at 19 17 12" src="https://github.com/user-attachments/assets/c5b05584-45ea-47f7-b04e-3692435a8eed">

<img width="340" alt="Screenshot 2024-10-25 at 19 17 25" src="https://github.com/user-attachments/assets/cd3d77f1-0309-41e7-9fdb-a1a8e01a46c7">

**Comment by devkiran** [comment]
Thanks for pointing this out. Feel free to create a PR. I think you should update the zod schema `createUTMTemplateBodySchema` to trim.

**Comment by steven-tey** [comment]
thanks for reporting! awarded 150 points for the bug report, another 150 for the fix :)

**Comment by unrenamed** [comment]
> Thanks for pointing this out. Feel free to create a PR. I think you should update the zod schema `createUTMTemplateBodySchema` to trim.

@devkiran In Zod, the order in which you call methods matters. This seems to be the root cause. There are only 2 files in API schemas that use `trim()` after the `min(1)` check; **the rest look good**. I'll push the fix in a moment.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/c6e4446f-8e16-4831-851f-232c00379b36">
