### ISSUE TITLE
Unrecoverable state when using PRO feature on Free Plan while adding a new domain

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1650]
### Issue Summary

When a user on a Free billing plan attempts to use a PRO feature while creating a new domain, the process enters an unrecoverable state. After an error message is displayed in a toast notification, the "Add domain" submit button remains disabled and shows a loading indicator. The user must close the modal window entirely to attempt creating a domain again.

### Steps to Reproduce

1. On a Free billing plan, go to `Settings > Domain`.
2. Click `Add Domain` to open the domain creation modal.
3. Attempt to use PRO-only features while setting up the new domain — fill `Default Expiration URL` and `Not Found URL` inputs.
4. Observe that an error message appears in a toast notification.
5. Note that the "Add domain" button is disabled and displays a loading indicator indefinitely.

### Expected Behavior
When an error occurs due to the use of a PRO feature on a Free plan, the "Add domain" button should re-enable, allowing the user to adjust their settings and resubmit without closing the modal. The loading indicator should disappear after the error notification.

### Reproduction Video

https://github.com/user-attachments/assets/2a196876-3688-4937-a374-c07c634efd73

**Comment by DeepaPrasanna** [comment]
What a coincidence! I was about to create the same issue now.

**Comment by DeepaPrasanna** [comment]
The button's behaviour is same while adding an archived domain

**Comment by steven-tey** [comment]
/award 150 thank you! this should be a super simple one-liner fix – assigned it to you @unrenamed
