### ISSUE TITLE
CSV download option visible to non-business users on Events page, causing unclear error

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1651]
### Issue Summary

On the Events page, users with a billing plan lower than Business can see the option to download a CSV of the Real-time Events Stream, but clicking it results in a vague "Error" toast message. This error message does not explain the root cause, and ideally, the CSV download option should be hidden for users on plans below Business since the feature is not accessible to them.

### Steps to Reproduce

1. Log in with an account on a billing plan below Business.
2. Navigate to the `Events` page.
3. Attempt to download a CSV of the Real-time Events Stream by clicking the download option.
4. Observe the "Error" toast message that appears without further explanation.

###  Expected Behavior

For users on plans below Business, the CSV download option ideally should be hidden, preventing access to features not included in their subscription. 

### Alternative approaches

If the option remains visible, a clear error message should appear, explaining that CSV downloads are available only for Business plans.

### Reproduction Video

https://github.com/user-attachments/assets/3253c9b2-4fa4-4c78-827d-48b81dd7c56e

**Comment by steven-tey** [comment]
/award 150 great catch! Lets go ahead and disable the download csv button (not the `⋮` dropdown) when `plan === 'free'` or `plan === 'pro'`
