### ISSUE TITLE
Bug: Undoing an archived/unarchived link doesn't displays proper message on the toast

### ISSUE THREAD

**Issue by DeepaPrasanna** [dubinc/dub#1652]
After clicking on the undo button on the message toast when archiving or unarchiving a link, it doesn't displays a proper message, instead shows this: 

Where?
![Screenshot 2024-10-25 230310](https://github.com/user-attachments/assets/2ee1c859-392e-41d2-af7a-70ad543e9e3b)

Problematic behaviour:
![image](https://github.com/user-attachments/assets/6f755f0b-93cd-4fab-830d-5bf57838c0b5)

Expected behaviour:
To show the message properly: Archived/Unarchived successfully

**Comment by Naprila** [comment]
I would like to work on this issue.
And it would be nice if it would be mentioned how to reproduce the issue.

**Comment by DeepaPrasanna** [comment]
Hey @steven-tey , as I pointed out the issue, I want to work on this :)

**Comment by unrenamed** [comment]
@DeepaPrasanna 👋 let me know if you're not planning to work on this. Since I implemented this undo feature, I'd  be happy to fix this.

**Comment by steven-tey** [comment]
assigned to you @unrenamed

**Comment by DeepaPrasanna** [comment]
> @DeepaPrasanna 👋 let me know if you're not planning to work on this. Since I implemented this undo feature, I'd be happy to fix this.

I planned to work on this today. But it's fine. :)
