### ISSUE TITLE
No URL validation for the referral field in the utm template 

### ISSUE THREAD

**Issue by DeepaPrasanna** [dubinc/dub#1655]
I was expecting the referral to have a URL validation as it was showing a URL in the placeholder. But it can also accept non URLs.

https://www.loom.com/share/10c3c498ef734efbb59fd0be00f906f7?sid=ed717030-8247-48c8-81be-cc564daf7c01

**Comment by steven-tey** [comment]
`ref` does example non-URLs (e.g. `ref=product-hunt`)
