### ISSUE TITLE
Unverified Domain Transfer Shows Validation Error but Completes in Background

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1674]
### Issue Overview

When a user attempts to transfer an unverified domain to another workspace, an error tooltip appears with a validation failure message. However, the domain transfer appears to complete in the background, as the user receives a **domain transfer completed** email notification. The transfer request fails with `422 Unprocessable Content` status.

### Steps to Reproduce

1. Log into the application and create a new workspace if you only have one.
2. Navigate to your main workspace domain management: `Settings > Domains`
3. If you don't have an unverified domain, add a new one and do not verify it. It should display a red `Invalid` tag.
4. Attempt to transfer an unverified domain to a different workspace.
5. Observe the error tooltip displaying a validation failure message: `Error: invalid_type: registeredDomain: Required
`
6. Reload the page to ensure the domain was removed from your main workspace. 
8. Check if the "Domain Transferred" email is received.

### Expected Behavior

The domain transfer should either complete without displaying an error or halt entirely if it fails validation, ensuring the email notification aligns with the actual transfer status.

### Replication Video

https://github.com/user-attachments/assets/17a055b4-059c-4f1d-b35b-ea7cb31ccf1c

### Screenshots

<img width="551" alt="image" src="https://github.com/user-attachments/assets/6507d35e-77e8-4ac8-bae8-410394ef6e7b">

**Comment by steven-tey** [comment]
assigned to you @unrenamed!
