### ISSUE TITLE
[🎨 Design Proposal] Align `Ggl.link` home page title with Google's official colors

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1675]
### Description

Just wanted share this proposal that aims to enhance https://dub.co/tools/google-link-shortener page.

The idea is to update the gradient colors for the "Google" portion of the title to align with Google's official colors . This adjustment might not only create a visually appealing effect but also ensure consistency with other branded domains and their homepages (e.g. Amazon, Spotify, Figma).

A screenshot with an example is provided below for reference.

<img width="1722" alt="image" src="https://github.com/user-attachments/assets/b679d3b0-31b8-4a3c-b0a9-c347067bd087">

<img width="1725" alt="image" src="https://github.com/user-attachments/assets/77ad5fd5-4db1-4005-a64e-9a45f9c75b60">

WDYT?

**Comment by Miskat360** [comment]
interesting issue

**Comment by steven-tey** [comment]
actually tried that before but it looked odd, so decided to go with b&w – thanks for the suggestion though!

**Comment by unrenamed** [comment]
ugh, right.. forgot for a sec using a wrong mix of colors may land me in court. wild times 🥲
