### ISSUE TITLE
Error Toast on "Enable" Button Click in Dub CLI Integration

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1676]
### Issue Overview

When attempting to enable the Dub CLI Integration by clicking the "Enable" button on the respective page, users encounter an error toast stating `Invalid integration slug.` The action does not result in any further prompts or modals, leaving users uncertain about the feature's status and expected behavior.

### Steps to Reproduce

1. Navigate to the Dub CLI Integration page: `Your Workspace > Settings > Integrations > Dub CLI`
2. Click on the "Enable" button.
3. Observe the error toast that appears.

### Expected Behavior

Upon clicking the "Enable" button, the integration should either:
- Successfully enable the Dub CLI Integration, potentially showing a success message or modal for further configuration, if applicable.
- If the feature is still in beta, a clear message should inform users of this status, along with guidance on the next steps. 

### Reproduction Video

https://github.com/user-attachments/assets/ec0ba9f6-27d4-4d59-a9cd-ea71bf150f81

**Comment by steven-tey** [comment]
This has been fixed!
