### ISSUE TITLE
[📄 dubinc/docs] Add Missing Step to Local Setup Guide for Dub

### ISSUE THREAD

**Issue by unrenamed** [dubinc/dub#1679]
### Description

A PR is being created for the `dubinc/docs` repository to include a crucial step in the local setup guide for Dub. This step will suggest compiling the internal packages used by the web application, ensuring that users have a complete and functional setup process.

Link to PR: https://github.com/dubinc/docs/pull/106

### Further improvement

The command suggested in the PR can be registered in the root package.json under the scripts section for easier use and memorization.

Additionally, we could implement a `postinstall` hook to automatically build all internal packages (only from the `packages` folder, excluding `apps/web`). However, this would introduce some overhead, as rebuilding would occur when installing or removing any single dependency. This aspect is open for further discussion.

**Comment by steven-tey** [comment]
amazing work, thank you!
