### ISSUE TITLE
Disallow SEO to list dub base domain

### ISSUE THREAD

**Issue by jdbruxelles** [dubinc/dub#1700]
When I search on Google for my project, I got the dub custom domain in the results. Would be nice to disallow search engines, or to have an option to disallow.

**Comment by steven-tey** [comment]
Hey @jdbruxelles! Dub custom domains have `noindex` by default: https://d.to/noindex

Do you mind sharing which domain this is so I can take a look?

**Comment by jdbruxelles** [comment]
Hey Steven. Yes, here is a [Google result](https://www.google.com/search?q=link+crfev) and the domain is link.crfev.bruxelles.dev

**Comment by jdbruxelles** [comment]
👋 Hi @steven-tey

**Comment by steven-tey** [comment]
Hi @jdbruxelles! Just checked this and it looks like only the root domain is indexed on Google:

![CleanShot 2024-11-15 at 15 49 58](https://github.com/user-attachments/assets/c4931744-2f34-4b0a-ae4f-174d6f8c3f46)

To fix this,  you can [set a redirect for your root domain](https://dub.co/help/article/how-to-redirect-root-domain), which will prevent the domain from being indexed.

**Comment by jdbruxelles** [comment]
Hi @steven-tey. Apparently I don't really have a choice. I don't have access to the proposed solution and I can't upgrade to the pro plan at the moment. Thank you :)
