### ISSUE TITLE
Build failes to deploy becuase of vercel function size

### ISSUE THREAD

**Issue by Husky-Devel** [dubinc/dub#1705]
![382424704-49fa949e-be7e-4686-81f0-5027cd4c9ad1](https://github.com/user-attachments/assets/4f9a2a41-79af-4e37-91e4-a02395efddfe)

Build log... https://pastebin.com/kkC3xAFh

**Comment by steven-tey** [comment]
Will take a look at how we can optimize this, but in the meantime, a workaround would be to deploy with a Vercel Pro plan: https://vercel.link/edge-function-size
