### ISSUE TITLE
Local setup giving error

### ISSUE THREAD

**Issue by aeswibon** [dubinc/dub#1708]
# Bug

## Description

While attempting to set up the project locally in accordance with the documentation’s instructions, I encountered difficulties with the Tinybird setup section. Upon executing the `tb push` command to push the datasources and pipes, an error message was generated indicating the absence of the resource “dub_links_metadata_lambda.”

## Screenshot

<img width="816" alt="Screenshot 2024-11-12 at 17 09 27" src="https://github.com/user-attachments/assets/60b3aa36-0df9-43c4-a919-6930e28ea2e3">

<img width="816" alt="Screenshot 2024-11-12 at 17 09 46" src="https://github.com/user-attachments/assets/64d8e528-b3c5-407a-b417-861b429dc697">

## Solution

To resolve the error, the datasource file `dub_links_metadata_lambda` must be added to the `packages/tinybird/datasource` folder.

## Steps to reproduce

1. Clone the repository and install the required dependencies.
2. Compile the dependencies.
3. Authenticate to tinybird using the CLI and then attempt to push the datasources and pipes using the `tb push` command.

**Comment by devkiran** [comment]
This has been fixed now.
