### ISSUE TITLE
Outdated local development guide

### ISSUE THREAD

**Issue by abhinav700** [dubinc/dub#1735]
It looks like the local development guide is outdated and does not reflect the current codebase.

Eg: there is no .env.example file in the directory

`tb push` step fails command fails ( I have tried this in multiple devices ) etc.

![image](https://github.com/user-attachments/assets/3870d2fe-190e-4d28-938a-abede93b6a5d)

**Comment by steven-tey** [comment]
should be fixed now!

**Comment by abhinav700** [comment]
@steven-tey but there is still no .env.example in root dir
![image](https://github.com/user-attachments/assets/cac0a8c7-2c54-427d-8cb6-824a401c28d9)
