### ISSUE TITLE
bug: can't exit search bar using ESC key (to use keyboard shortcuts again)

### ISSUE THREAD

**Issue by daallgeier** [dubinc/dub#1780]
1. I was searching for a link using the search bar but could not find it.  
2. Thus i wanted to create a new one.  
3. I went to press ESC and `c`

### Expected
I expected the new link modal to show up

### Actual Result
I searched for `C`

**Comment by steven-tey** [comment]
@daallgeier ha! good one – will get this fixed, thank you 🙏

**Comment by steven-tey** [comment]
fixed by #1824, h/t @michaltarasiuk
