### ISSUE TITLE
bug: creating a new tag in the edit link modal doesn't allow to save the edit

### ISSUE THREAD

**Issue by daallgeier** [dubinc/dub#1781]
similar to: #1654

1. Edit existing link 
2. Create and Assign new tag
3. Try to save link
4. Exit link

### Expected
(3) Save Icon turns from greyed out to solid
(4) Link gets saved with new tag 

### Actual
(3) Save Icon stays grey
(4) Tag isn't assigned 

5. Edit link again 
6. Try to find tag (can't be found)
7. Exit Link and Refresh page
8. Tag shows up and can be assigned 
9. Finally Save

**Comment by steven-tey** [comment]
ah yes I've seen this before as well, will fix 🙏
