### ISSUE TITLE
Ability to store/reuse UTM params

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#180]
> The ability to store/reuse UTM params. We have multiple people creating shortlinks, and I worry that they'll use a _ instead of a - or something or capitalize Twitter and then we lack consistency in our tracking. We also want to make sure everybody is pulling from the same list of campaigns...
> 
> That's very much a nice-to-have, but it would be cool for me. Right now we store our UTM codes in Airtable and have to cross reference when we build links in Dub.

**Comment by salman0ansari** [comment]
much needed.
