### ISSUE TITLE
Removing a tag while editing an existing link breaks the website

### ISSUE THREAD

**Issue by hkirat** [dubinc/dub#1810]
I tried editing an existing link. I removed a tag from it (there was only 1 tag in there)
As soon as I unselected the tag, the website crashed

<img width="1862" alt="Screenshot 2024-12-19 at 5 05 51 PM" src="https://github.com/user-attachments/assets/a231a82a-9652-4526-838b-44ce30ec9d03" />

**Comment by hkirat** [comment]
Cant re-produce it reliably

**Comment by steven-tey** [comment]
thanks for the report, fixing!
