### ISSUE TITLE
can't sign in, sign up

### ISSUE THREAD

**Issue by naddika** [dubinc/dub#247]
I'm trying it locally. Instead of letting me sign up or sign in locally, it'll redirect me to the https://app.dub.sh/login for it

But a  link for signing in contains **localhost**:

![Screenshot_20230703_022015](https://github.com/steven-tey/dub/assets/44301454/d2bb6a2b-760b-4754-9879-8860f19d8fcb)

How to create a local user manually?

**Comment by steven-tey** [comment]
Related to #12, closing for now
