### ISSUE TITLE
Assign multiple tags to links

### ISSUE THREAD

**Issue by john-vargo** [dubinc/dub#295]
As noted [here](https://dub.sh/help/article/how-to-use-tags#can-i-assign-multiple-tags-to-a-link), dub.sh only allows a single tag to be assigned per link.  Our use case would benefit from multiple tags per link.  Additionally, when using the filter view, we would request this enhancement allow but an "OR" as well as an "AND" criteria for filtering links.  I.e., when filtering the links in a project, if multiple tags are selected, the "OR" selection would present any links matching either tag, and the "AND" selection would present only links that match all selected criteria.

**Comment by askprateek** [comment]
Please add support for multiple tags. This feels like a basic feature to have with this awesome product. :)

**Comment by pavelklymenko** [comment]
It will be awesome if it will be implemented per the initial comment by @john-vargo (multiple tags support and filtering). @steven-tey thanks for working on this.

**Comment by akash1520** [comment]
@steven-tey can I work on this? If the filtering part is still left to do?

**Comment by steven-tey** [comment]
Will be doing a proper announcement for this soon, but we recently shipped support for multiple tags for a given link! 

Also updated the [guide](https://dub.co/help/article/how-to-use-tags#can-i-assign-multiple-tags-to-a-link) as well:

<img width="741" alt="CleanShot 2024-03-12 at 13 17 06@2x" src="https://github.com/dubinc/dub/assets/28986134/234a41d7-4036-4798-aa11-33b3b4dbaa22">

**Comment by steven-tey** [comment]
Announcement blog post is live: https://d.to/tags

Thanks again for all the feedback here guys!
