### ISSUE TITLE
Generate QR code for root domain redirects

### ISSUE THREAD

**Issue by Nezteb** [dubinc/dub#308]
You currently can only generate QR codes for regular links, like `mysite.com/abcde`.

If you are a paid Dub user, you are unable to generate QR codes for domains like `mysite.com` by itself.

I just signed up for the pro plan and was confused that this feature wasn't a thing. 😅

**Comment by steven-tey** [comment]
So sorry it took so long for this to be fixed, but we finally added this feature 🙏
