### ISSUE TITLE
[Bug] New Mobile Edit Link Menu Easily Closes & Glitchy With Keyboard Input

### ISSUE THREAD

**Issue by abass** [dubinc/dub#309]
This is best shown in a Loom video:
https://www.loom.com/share/f79204f705e04789ba9ee953273311d5

**Comment by KSSaiTeja** [comment]
i will work on this issue, hey @abass can you please tell me how can i reproduce this and work upon it!

**Comment by abass** [comment]
Amazing! Thanks @KSSaiTeja—I sent a few more videos to @steven-tey, here's another one:
https://www.loom.com/share/fe779d11ceda48b5b843314864d23148

So tough to say for certain, I'm on a Pixel 7 using Google Chrome. Sounds like this issue doesn't happen with iOS? So possibly the only way to reproduce is to use an Android device to test it? 😥

**Comment by zlwaterfield** [comment]
@steven-tey the cause of this seems to be around the styling (tags-section.tsx)[https://github.com/dubinc/dub/blob/main/apps/web/ui/modals/add-edit-link-modal/tags-section.tsx]. Do you remember why this was built this using (cmdk)[https://www.npmjs.com/package/cmdk]? It seems a bit overengineered, and it's hard to debug because there's a ton of logic and styling altered that probably doesn't need to be there.

**Comment by steven-tey** [comment]
Ah yes, I'm happy to refactor that since we'll also need to think of a way to accommodate #449 as well

**Comment by steven-tey** [comment]
Just pushed a change that should fix this – let me know if it's still causing an issue: 

https://github.com/dubinc/dub/assets/28986134/9ba0e72f-5805-4ef1-8453-ef2122894d45

We'll still need to implement the multi-tag approach, but will leave this for #449

**Comment by abass** [comment]
Hmm, it doesn't seem all that different, still completely unusable on mobile. Any chance you have an Android device on Chrome you could test it with? Constant white screen segments and inability to even scroll down:
https://www.loom.com/share/53dbb95cf4e74f47927ad23d3431aad7

I used to be able to scroll down at least, but haven't been able to even do that for a few weeks/months now 😅
