### ISSUE TITLE
Default by Number of Clicks Instead of Date Added

### ISSUE THREAD

**Issue by abass** [dubinc/dub#328]
Finding that I actually rarely if ever care about first seeing the "last added" at the top the longer that I use Dub. When first arriving to Dub and doing any filtering/searching, I'm almost always curious about the most engaged link for the filter, and just in general.

This introduces 2 additional mouse clicks every time I do anything in Dub:
![CleanShot 2023-08-23 at 19 33 08](https://github.com/steven-tey/dub/assets/5505994/530576d9-ec8e-4edb-ac61-3ab44d544bc9)

I would be curious to even hear from one person that would prefer seeing based on date added as a heavy user of Dub. The date a short link is added is often irrelevant to it's importance/what you're likely looking for, whereas number of clicks is definitely a more useful metric of priority.

**Comment by fazlerocks** [comment]
When dealing with a large number of links, it would be preferable to have them sorted by date. For some, it's valuable to see the performance of recent links rather than tracking ones that were shortened months ago. A better solution would be to remember the user's last sorting option and set it as the default for their next visit.

**Comment by abass** [comment]
Hmm, that's fair. And the specific UX for creating and top clicks being shown would make it immediately disappearing makes sense as being jarring if so.

It's just that for us, every time we visit Dub, it's useless links being shown 99% of the time, never what I'm looking for, especially when filtering down further, and I see this just getting worse with more time. Could it at the very least remember the sort method for the current session? Ideally for the account until log-out and back in for example?

It could show any created links during that session in the top area, and upon refresh it respects the sorting method

Just finding that every time I visit Dub now, I'm greeted with links of no use because I'm often spinning up a link here and there for the website. Especially when the API comes and more programmatic links are generated. It's going to be sooooo much noise.

**Comment by thevinitgupta** [comment]
I agree with the number of clicks response on the UI landing.
As for @fazlerocks your idea is correct about the performance pressure on the database.
What we could do is have a cached data list for the same. 

We can rebuild the cache during a predefined times(at night or when the users visit counts are the lowest)

**Comment by steven-tey** [comment]
This should be possible now with the [new links dashboard](https://dub.co/blog/new-links-dashboard) :D
