### ISSUE TITLE
Feature request: Invite links

### ISSUE THREAD

**Issue by zeke** [dubinc/dub#337]
I would like to generate a reusable invite link I can share with my teammates.

This would prevent me from being a bottleneck to getting them using the service, as they currently have to request access from someone and then wait for a one-off invitation:

![Screenshot 2023-08-26 at 12 15 27 PM](https://github.com/steven-tey/dub/assets/2289/22b1292b-0947-43d4-8d9d-41d17a42489e)

**Comment by steven-tey** [comment]
Took a while, but we finally shipped this: https://d.to/invites <picture data-single-emoji=":proud:" title=":proud:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/proud/0d66d0afe27c8514.png" alt=":proud:" align="absmiddle"></picture> 

![invite-links](https://github.com/dubinc/dub/assets/28986134/add5f811-83d9-4ebc-a7e6-4d9fe5bffc31)
