### ISSUE TITLE
Add status page

### ISSUE THREAD

**Issue by fmerian** [dubinc/dub#357]
could use [this page](https://dub.openstatus.dev/) (powered by [openstatus.dev](https://github.com/openstatusHQ/openstatus)) (not sure who made this, tho! any idea @thibaultleouay @mxkaske?)

also happy to handle it! I'm thinking of adding it in the footer.

![Link to Dub Status Page in footer](https://github.com/steven-tey/dub/assets/1890087/7ac9a51d-8778-419b-8991-22149753faf7)

**Comment by mxkaske** [comment]
Pretty sure it was @steven-tey himself. 😉

**Comment by fmerian** [comment]
> Pretty sure it was @steven-tey himself. 😉

no kidding!? awesome! then I suppose I can push it forward and create the PR

**Comment by kushalag** [comment]
I can see that this ticket is still open, should i go ahead and make a PR which adds the status link in the footer? Also it would be helpful if i can know under which menu item (Product, Company, etc.) should it be placed
