### ISSUE TITLE
[Feature Request] allow adding subdomains to different projects

### ISSUE THREAD

**Issue by natterstefan** [dubinc/dub#407]
Hi @steven-tey,

We use the following schema for our environments:

```bash
# <subdomain>.<env>.domain.com
l.dev.example.com
l.staging.example.com
l.example.com
```

I can create different projects for different environments, but only if they use different domains. In other cases, they have to share the same project. This is impractical (at least for us) as we do not want the data (later on if a global dashboard exists #278) mixed between environments.

Could you tell me what the reason behind this decision is? For instance, one can split projects on Vercel by (sub)domains.

Thanks for your help. :)

PS: I know one can filter links in the UI, but that requires us always to filter if we want to look at production only, whereas splitting projects by domain removes that task. 🤔 

### Related Code

https://github.com/steven-tey/dub/blob/a2a4f43eb5f606eb159a59e882418aefdbee9264/lib/api/domains.ts#L33-L65

**Comment by steven-tey** [comment]
Ah yes, this is a security measure, but we can probably add a way to allow you to add a subdomain to a different project if you are the part of the first project that has the domain. Will get this fixed 🙏

**Comment by natterstefan** [comment]
Thank you @steven-tey!

**Comment by steven-tey** [comment]
This should be fixed now :)
