### ISSUE TITLE
Confusing UX when trying to create a link for root domain

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#411]
![CleanShot 2023-10-10 at 08 57 49](https://github.com/steven-tey/dub/assets/28986134/eda0ccc0-02ab-49e3-adc9-f10c0faccbe7)

Should add documentation & link to the domains tab and/or upsell to Pro

**Comment by toufiqfarhan0** [comment]
Heyy @steven-tey  i want contribute can you help to setup locally, I'm getting error

**Comment by T1LT** [comment]
hi @steven-tey is this issue still open? I would love to take a look at this if it is!

**Comment by steven-tey** [comment]
@T1LT  Yes it's still open – feel free to go for it! :)

**Comment by T1LT** [comment]
@steven-tey looks like this is already fixed in prod, unless I'm missing something?

![image](https://github.com/dubinc/dub/assets/65653163/9b114da1-3d69-4d91-8e5f-c87def125f55)

**Comment by steven-tey** [comment]
Ahh yes, sorry about that – let's go ahead and close this out for now! :)
