### ISSUE TITLE
Public Share Link Not Respecting Our Pro Plan (last 3/mo + All Time)

### ISSUE THREAD

**Issue by abass** [dubinc/dub#421]
Was experimenting with this share page:
![CleanShot 2023-10-20 at 14 27 24](https://github.com/steven-tey/dub/assets/5505994/c60d2869-3fdd-461d-a36d-cb0000a3d44f)

Noticed though that it's not respecting that we are on the pro tier. That said, really would need password protect capabilities before we'd be able to use this functionality.

**Comment by steven-tey** [comment]
This has finally been fixed by #1596 🥹
