### ISSUE TITLE
"Body exceeded 1500kb limit" error when I add an image to a link

### ISSUE THREAD

**Issue by max-samusevich** [dubinc/dub#423]
Hello!
I have a custom domain, I set it and tried to create a first link. If I add an image (a link preview) to the link, I get a push notification "Body exceeded 1500kb limit" (attached image 1) and can't save the link. If I create a link without an image, the link is being saved and works fine. I tried to reload page with cache clearing, it doesn't help.
I tried a few images, 1.2mb, 2.3mb, the result is the same even if the limit for an image size is 5mb.

In the Network tab of Chrome Dev Tools I see that the image I try to add as a link preview is loaded as base64 with 200 code with a "from memory cache" remark (attached image 2).

I also see a stack of errors in the Console and the Network tabs: 2 things about favicons that are appearing again and again with time with 301 and 404 codes (attached image 2), and PUT requests with 413 errors when I click a button to save the link with the link preview image (attached image 3).

What are these errors and how to fix them? How to add images to links?

![2023-10-23_15-09-45](https://github.com/steven-tey/dub/assets/30405901/3887bce1-e814-4ad2-82bc-e20724b96ff6)

![2023-10-23_15-33-18](https://github.com/steven-tey/dub/assets/30405901/e7a0329a-ae9f-4f6e-a269-f31dace1863d)

![2023-10-23_15-21-12](https://github.com/steven-tey/dub/assets/30405901/a1d2d8fd-1d79-4304-b9ef-3e41972c647f)

**Comment by steven-tey** [comment]
This is a bug, will fix – thank you!
