### ISSUE TITLE
Metatags - Edge case: nothing detected on some websites

### ISSUE THREAD

**Issue by pablobarrera** [dubinc/dub#427]
Hi, I have been using the metatags api to generate link previews and I found this edge case:

**Nothing detected:**
Link: https://www.fastcompany.com/90970396/how-asking-the-right-3-questions-can-inspire-great-leadership

Metatags don't detect anything:
<img width="529" alt="Screen Shot 2023-10-24 at 11 54 47" src="https://github.com/steven-tey/dub/assets/16086326/e021c616-593e-4074-a3c0-759c18e31dfa">

LinkPreview.net detects properly:
<img width="1089" alt="Screen Shot 2023-10-24 at 11 55 10" src="https://github.com/steven-tey/dub/assets/16086326/5f52a030-dfdf-48e2-8cec-2c3f747dd10c">

And the following cases don't work on both Metatags and LinkPreview.net, I'm not sure if something could be done:

**Images don't have a preview**
https://cdna.artstation.com/p/assets/images/images/002/426/200/4k/helena-butenkova-forest-army-by-acidea-da0bvg4.jpg?1461609843

**Nothing detected**
https://www.inc.com/justin-bariso/emotional-intelligence-how-to-reach-goal-be-successful.html

**Comment by omkar342** [comment]
Hi @steven-tey, I would like to fix this issue. Will you please assign this to me?

**Comment by steven-tey** [comment]
@omkar342 just did – thank you!

**Comment by pablobarrera** [comment]
I leave two more cases, if you want I could create another issue for these.

**Nothing detected:**
Link: https://www.glassdoor.com/blog/tips-for-building-an-online-personal-brand/?utm_source=newsletter&utm_medium=email&utm_campaign=1023_us_newsletter&utm_content=20231026_personal_brand&cm=EMAIL_LIFECYCLE

Metatags don't detect anything:
<img width="527" alt="Screen Shot 2023-10-30 at 10 47 15" src="https://github.com/steven-tey/dub/assets/16086326/fe5e8a24-e9e4-4e38-a006-57fe5a39f4d3">

WhatsApp detects properly:
<img width="354" alt="Screen Shot 2023-10-30 at 10 47 41" src="https://github.com/steven-tey/dub/assets/16086326/0cc4cf6f-2ac6-4e2b-b96d-6ffd29756b99">

And for the following one, neither WhatsApp nor LinkPreview.net generates a preview so I'm not sure if something could be done:

**Google Drive Images don't have a preview**
https://drive.google.com/file/d/1Vmo0PnMSPJjnCmHI_A1aaR2KE2lMAC0D/view?usp=sharing

**Comment by kasperaamodt** [comment]
@steven-tey as far as I can see, these sites blocks bots or metadata scrapers. Is that not something Dub should honour? If not, it should be possible to get the metadata with a headless browser.

<img width="1092" alt="Screenshot 2024-10-01 at 21 56 59" src="https://github.com/user-attachments/assets/963aa937-c93d-4835-a343-97269d37213f">

**Comment by 01vishu** [comment]
@steven-tey some websites are detacting bot that's why we are not getting meta data from those website, we need to integrate anti bot detaction. So am I allow to add a library or try diffrent approch

**Comment by steven-tey** [comment]
@01vishu how are they detecting it? is there any way we can work around it?

**Comment by 01vishu** [comment]
@steven-tey like request patterns or maybe the are detacting javascript. We need use use proxies to prevent these kind of bot detaction. What do you think?

**Comment by a19hu** [comment]
@ManpreetKhinda are you woking on this isssue?

**Comment by ameghcoder** [comment]
@steven-tey Hey, I tried to set the dub. co in local development to solve the issue after doing everything correctly I got this error from next.js, Can you help me to solve this?
![Screenshot from 2024-10-12 16-42-57](https://github.com/user-attachments/assets/9d0cd488-1a75-49ca-abde-fce5b917dff7)

**Comment by steven-tey** [comment]
@ameghcoder try running `pnpm clean && pnpm i && pnpm dev`

**Comment by ameghcoder** [comment]
@steven-tey I run the above command but error is still same

**Comment by ameghcoder** [comment]
@steven-tey This error shows on localhost:8888/login path

**Comment by ameghcoder** [comment]
Setup is not working properly. So I'm out
/unassign

**Comment by steven-tey** [comment]
@Anky9972 are you still working on this?

**Comment by Anky9972** [comment]
@steven-tey Yes, I working on this. It will take some time.

**Comment by manish-lal12** [comment]
@steven-tey, I have put a pull request for this issue. Please review it...
