### ISSUE TITLE
Tag Analytics

### ISSUE THREAD

**Issue by tonyflo** [dubinc/dub#428]
I'd love to see analytics at the tag level. Feature request talked about here too #101

**Comment by steven-tey** [comment]
Great idea! Recently refactored our Analytics setup so we should be able to add this along with #278

**Comment by aakash2330** [comment]
i'd love to work on this .

**Comment by steven-tey** [comment]
Update: This turned out to be a bit more complex than just the scope of #278 so gonna have to push this to another PR 🙏

**Comment by steven-tey** [comment]
Good news – you can now filter analytics by tags: https://d.to/tags

![introducing-tags](https://github.com/dubinc/dub/assets/28986134/0b3a768d-2b58-4f02-b16b-bead2cdf0149)

Thanks again for all the feedback here guys!
