### ISSUE TITLE
Add Day of Week on Analytics Graph Hover

### ISSUE THREAD

**Issue by abass** [dubinc/dub#441]
Realizing that I'm often checking a calendar to see the day of the week as it would help us see trends when viewing links.

For example, traffic seems to drop on weekends, and Thursdays seem to be one of our biggest days for certain companies. Coming to this conclusion was a lot of work though, checking the date against a calendar 😁

This is the 4th time I've done this now and just realized that it could actually be a super simple feature 😂

![CleanShot 2023-11-04 at 20 42 34](https://github.com/steven-tey/dub/assets/5505994/6f6c510e-43bc-4596-a395-977431435eed)

**Comment by gaurab-khanal** [comment]
Can I work on this? @styfle

**Comment by steven-tey** [comment]
@gaurab-khanal sounds good! :)

**Comment by steven-tey** [comment]
Can't believe it took us so long to ship this, but we finally did:

<img width="987" alt="CleanShot 2024-04-14 at 22 47 16@2x" src="https://github.com/dubinc/dub/assets/28986134/208f64bc-ad4a-4e31-9fe2-8ee8a274fe69">

**Comment by abass** [comment]
Sooooo insanely helpful to know what days of the week are leading to dips/peaks, you have no idea! Thank you so much 🙏
