### ISSUE TITLE
Update X/Twitter card to reflect current 

### ISSUE THREAD

**Issue by o-az** [dubinc/dub#461]
Current X preview links no longer show link title and description. The dub dashboard still shows old Twittet card when creating a new link

**Comment by VishalMCF** [comment]
@o-az Can you please add more details? I would like to work on this issue

**Comment by o-az** [comment]
> @o-az Can you please add more details? I would like to work on this issue
> 
> 
> 
> Edit:- I understand the issue now. Here is what I tried
> 
> The post link from twitter/x => https://x.com/ATRightMovies/status/1723252216331448715?s=20
> 
> Here is the snapshot:-
> 
> <img width="1680" alt="Screenshot 2023-11-11 at 6 07 22 PM" src="https://github.com/steven-tey/dub/assets/70262922/94213699-a12b-4995-a7b0-91079e84d348">
> 
> 
> 
> 

Try to share a link on x.com, you will see it no longer displays the og description and og title. It only displays og image. So the Twitter card in the screenshot you shared is outdated layout.

**Comment by VishalMCF** [comment]
@o-az So you mean to say that it is a problem from twitter/x.com??

**Comment by o-az** [comment]
> @o-az So you mean to say that it is a problem from twitter/x.com??
> 
> <img width="608" alt="Screenshot 2023-11-12 at 2 33 34 AM" src="https://github.com/steven-tey/dub/assets/70262922/9d7d0c9e-2b34-4976-abbc-64d87408e0e9">
> 
> This is what I see after trying to share a youtube video link.
> 
> Can you please mention what should be the expected behavior?

Great catch, looks like YouTube links aren't affected. Only articles are affected. Try to post an article for example:

https://www.90min.com/posts/carlo-ancelotti-breaks-sir-alex-ferguson-champions-league-record

Another example:

https://fortune.com/2023/08/21/elon-musk-plans-remove-headlines-news-articles-link-shared-on-x-twitter/

Here's how it looks
 ![image](https://github.com/steven-tey/dub/assets/23618431/06cbb7e8-ac52-4643-b65b-1b396cf95ce1)

![image](https://github.com/steven-tey/dub/assets/23618431/2df695d4-00ad-4e56-9f1e-c7d1b8bd41bf)

**Comment by o-az** [comment]
> @o-az So you mean to say that it is a problem from twitter/x.com??
> 
> <img width="608" alt="Screenshot 2023-11-12 at 2 33 34 AM" src="https://github.com/steven-tey/dub/assets/70262922/9d7d0c9e-2b34-4976-abbc-64d87408e0e9">
> 
> This is what I see after trying to share a youtube video link.
> 
> Can you please mention what should be the expected behavior?

@VishalMCF Great catch, looks like YouTube links aren't affected. Only articles are affected. Try to post an article for example:

https://www.90min.com/posts/carlo-ancelotti-breaks-sir-alex-ferguson-champions-league-record

Another example:

https://fortune.com/2023/08/21/elon-musk-plans-remove-headlines-news-articles-link-shared-on-x-twitter/

Here's how it looks
 ![image](https://github.com/steven-tey/dub/assets/23618431/06cbb7e8-ac52-4643-b65b-1b396cf95ce1)

![image](https://github.com/steven-tey/dub/assets/23618431/2df695d4-00ad-4e56-9f1e-c7d1b8bd41bf)

**Comment by steven-tey** [comment]
oh yeah good point, will need to update this, thank you!

**Comment by amblerkr** [comment]
He broke Twitter. which already has embeds that don't work well on other platforms, even on Discord.
https://twitter.com/robots.txt 
![image](https://github.com/steven-tey/dub/assets/67187038/0bcb135e-cc68-4857-9482-0bda6f4013fa)

**Comment by steven-tey** [comment]
Finally got around to fixing this! Apologies for the delay here 🙏 

![CleanShot 2024-01-04 at 21 21 07](https://github.com/dubinc/dub/assets/28986134/28dcd26b-17c2-4b91-9aea-4827fff7aa58)
