### ISSUE TITLE
[Feature] Raycast extension

### ISSUE THREAD

**Issue by fmerian** [dubinc/dub#464]
with recent release of Dub's API public beta (#73), would love to have an extension for Raycast.

for the record, there's one for Bitly in the [Raycast Store ↗︎](https://www.raycast.com/blessanm86/bitly-url-shortener) that supports the following command:

- Shorten URL: Overwrite the clipboard contents with a shortened URL

thanks!

**Comment by tanayvaswani** [comment]
maybe I can give it a try

**Comment by fmerian** [comment]
> maybe I can give it a try

that'd be awesome! thanks, Tanay!

**Comment by fmerian** [comment]
recently stumbled upon [this Raycast extension](https://www.raycast.com/SebDanielsson/url-unshortener) that unshortens URLs. this could be a nice addition to the upcoming extension :)

**Comment by steven-tey** [comment]
Following up here – we still need to do a proper launch for this, but we do have a Raycast extension for Dub, courtesy of @quuu: https://dub.sh/raycast 🤩
