### ISSUE TITLE
Short link Exact Match Not Accounted for in Search Filter

### ISSUE THREAD

**Issue by abass** [dubinc/dub#465]
Sometimes I sanity check a short link in Dub (e.g. we hard-coded a URL in a video clip), so writing it out how we sees it in the video clip that our editor sent over, and then searching it in Dub, I would sorta expect it to show if you filter the entire URL (essentially, it's an exact match of the short link), but then I need to edit it to remove the URL. Then to ensure that I typed the short link correctly, I then use CMD + F.

Yes I can also just type in the URL and enter but I prefer to not get a click from that especially when I can do it without doing that by checking Dub.

Using site search for Dub:
![CleanShot 2023-11-13 at 10 43 12](https://github.com/steven-tey/dub/assets/5505994/a83b20e3-8db0-4bbb-8f3f-81fbbb76009e)

Dub's result:
![CleanShot 2023-11-13 at 10 41 33](https://github.com/steven-tey/dub/assets/5505994/79e62583-852a-4db5-9062-4e52dfdbf63e)

When removing the domain:
![CleanShot 2023-11-13 at 10 41 48](https://github.com/steven-tey/dub/assets/5505994/2ac4655f-6542-466b-a360-65e52944e4ab)

**Comment by steven-tey** [comment]
In the spirit of Hacktoberfest – would love to finally fix this once and for all. 

This will be split into 2 PRs:
1. Add a new column in the links table called `shortLink` with a unique index
2. Make sure we update the `shortLink` field in `createLink`, `updateLink`, `bulkCreateLinks`, `bulkUpdateLinks`
3. Remove the current `shortLink` polyfill that we're doing in `transformLink`
4. Add a script that backfills the `shortLink` field for existing links (`where: { shortLink: null }`)
5. Ship the PR to production first
6. Run the backfill script
7. In a follow-up PR, update the search logic to use the `shortLink` field instead `key`
8. Ship the second PR to production
