### ISSUE TITLE
[cron/domains] - will not send an email for the second unconfigured domains

### ISSUE THREAD

**Issue by mfts** [dubinc/dub#466]
It will only send a reminder email to the first unconfigured domain because the `sentEmails` will contain the enums set by the first unconfigured email and therefore the conditional will skip sending an email for each new unconfigured domain. 

https://github.com/steven-tey/dub/blob/main/apps/web/app/api/cron/domains/utils.ts#L163-L165

--- 
### solution

You have to store the `domain` in the `sentEmails` model because the emails are related to a particular domain.

**Comment by steven-tey** [comment]
Oh you're right, great catch! Will get this fixed, thanks a lot 🙏

**Comment by steven-tey** [comment]
Finally got around to fixing this issue – thanks again for reporting this @mfts! 🙏
