### ISSUE TITLE
Project fails to start on Windows: TypeError

### ISSUE THREAD

**Issue by owaisghaira** [dubinc/dub#474]
Environment

Operating System:
Windows 10

Node.js Version:
20.9.0

pnpm Version:
8.10.5

Steps to Reproduce

After Successful Build
Run the Project then got error
`pnpm dev`

Error
web:dev: [0] [TypeError: Cannot read properties of undefined (reading '')]
web:dev: [0]  ⨯ [TypeError: Cannot read properties of undefined (reading '')]
web:dev: [0]  ⨯ [TypeError: Cannot read properties of null (reading 'default')]
![Screenshot 2023-11-23 201314](https://github.com/steven-tey/dub/assets/64693690/195ced8b-7064-4965-a692-9cbd8600b34e)

**Comment by devkiran** [comment]
Can you try the latest version?
