### ISSUE TITLE
Allow adding titles to links.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [dubinc/dub#484]
If you look at https://linksta.cc/studio/links, you'll see that each entry has a title which has typographic predominance over its hyperlink. This is not true for https://app.dub.co/links, which makes quickly identifying the purpose of each link difficult.

> ![image](https://github.com/steven-tey/dub/assets/42837531/217481f4-544a-4057-860d-92d7ab5aabaa)

How am I to know what directs where? (Ignore the Google one.)

This is strange, considering that its uses the correct typographic hierarchy - it merely provides predominance to the link identifier. I consequently propose that we add a field for a link title. This is intended solely as an aid to the link manager - I don't care whether the link follower ever sees this, even in link previews.

In order to necessarily modify the GUI to accommodate this modification, I propose that https://app.dub.co/links adopt (or at least add) a table style, which I have tracked separately at https://github.com/steven-tey/dub/issues/485#issue-2021790145:

> This is because as the attribute presentation becomes more complex, keeping the GUI understandable shall become difficult to the extent that it may stifle improvements.

**Comment by harshbsharma** [comment]
Hey would like to discuss more and work on it.

**Comment by steven-tey** [comment]
Good news – you're able to customize the displayed properties in link cards with the [new links dashboard](https://dub.co/blog/new-links-dashboard#display-properties-customization) :)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/dubinc/dub/issues/484#issuecomment-2272223763

@steven-tey, that's damn near perfect, but I rather wanted to be able to add custom titles. Some domains, like `linkedin.com`, generally don't set the `<title>` element, meaning that all I see is "LinkedIn".
