### ISSUE TITLE
Exporting Analytics Data

### ISSUE THREAD

**Issue by Prajwalprakash3722** [dubinc/dub#488]
Our organization uses Prometheus and Grafana to view analytics, and we would really love to have all the analytics in one place. Is there any way to export the data periodically?

**Comment by ranjithjupaka** [comment]
Hey, yes there is a way to export data periodically. we can use Prometheus API to get the data programmatically and Grafana supports scheduled exports to export and send data periodically. I can work on this

**Comment by tonyflo** [comment]
Exporting analytics data is especially important [now that all paid Dub plans have limits on analytics retention](https://dub.co/blog/new-pricing). Pro and Business plan changed from unlimited link history to 1 and 2 years respectively.

**Comment by steven-tey** [comment]
@tonyflo thanks for the callout – will get this prioritized soon <picture data-single-emoji=":salute:" title=":salute:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/blob_salute/f7fc9045f76a0d4b.png" alt=":salute:" align="absmiddle"></picture>

**Comment by Prajwalprakash3722** [comment]
I can work on this if you want ? @steven-tey

**Comment by Prajwalprakash3722** [comment]
A hacky fix if you self host dub, you can just plug MySQL with grafana and write SQL queries :)

**Comment by steven-tey** [comment]
@Prajwalprakash3722 sure, thank you! A good approach would be the way Plausible handles this: https://plausible.io/plausible.io

**Comment by Prajwalprakash3722** [comment]
Let me clarify, do we want to export the analytics as:

- API
- Download option
- Expose it in Prometheus metric format

Plausible supports options 1 and 2.

**Comment by steven-tey** [comment]
Let's start with the Download Option @Prajwalprakash3722 🙏

**Comment by Prajwalprakash3722** [comment]
Alright 🆗

**Comment by steven-tey** [comment]
Wanted to follow up here – this feature has been shipped: https://d.to/export

Shoutout to @flornkm for building this out!
