### ISSUE TITLE
[FEAT]: `dub` CLI

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#506]
Building on @sujjeee's incredible work: https://github.com/sujjeee/dubco

## Proposal 

`npm i dub-cli`

Add an alias from `dub-cli` to `dub`

## Commands

- `dub help`: Shows a list of commands that are available
- `dub login`: [Login to Dub.co](https://github.com/sujjeee/dubco#initialize-config) via API token. 
	- Bonus: Auto-open a new window and log user in, but would require programmatic API token generation. Example: https://github.com/unkeyed/examples/tree/main/unkey-cli
- `dub config`: [Show current config](https://github.com/sujjeee/dubco#show-config)
	- Current user email
	- Current project
	- Current domain
-  `dub config set`: Set current config
	- Project selector
	- Domain selector
	
	Example:

	```
		? Switch to:
	  ── Projects ────────────────────────
	○ Dub (dub)
	○ Steven Tey (steven)
	○ One Word Domains (owd)
	  ─────────────────────────────────
	○ Cancel
	```
- `dub shorten [url] [key]`: [Shorten a URL](https://github.com/sujjeee/dubco#create-shortlink)
	-  If `url` and `key` are not provided, go through the current flow:

		```
		✔ Enter your Destination URL : … 
		✔ Enter your Short link : …
		✔ Short link created!
		```
	- If `url` is provided, create short link with random key
	- If both `url` and `key` are provided, create short link with provided key

## MVP notice 

This is the early MVP of the `dub` CLI and will be improved in the future!

**Comment by sujjeee** [comment]
🙋‍♂️

**Comment by VishalMCF** [comment]
@steven-tey @sujjeee I have one idea related to this. A few days back there was an issue created by you @steven-tey  to programmatically create the QR Code which I wanted to work on. Do you think it will be a good idea to let the user create the QR code by adding some extra parameters and let it download in the user file path? 
From there he can also then do many things like storing it in his S3 or Redis cache. 
What do you guys think?

**Comment by sujjeee** [comment]
https://github.com/dubinc/dub/assets/101963203/5c033536-f6c3-424b-94f0-88e6f01d42e4

**Comment by sujjeee** [comment]
@VishalMCF 👀


https://github.com/dubinc/dub/assets/101963203/594a26c2-a53d-4968-a543-e90a144e106c

**Comment by VishalMCF** [comment]
@sujjeee  Great!! You stole my potential issue already :)

**Comment by sujjeee** [comment]
@VishalMCF I realized that I have a simpler solution for this, so i implemented it.

**Comment by VishalMCF** [comment]
Is there anything that I can implement? If you have any idea?

**Comment by VishalMCF** [comment]
@sujjeee Is there anything that I can implement? Maybe you have something in your roadmap for the cli application?

**Comment by sujjeee** [comment]
You can try building a Dub React library. 

Take a look at OpenAI's and Cloudinary's React libraries for inspiration.

**Comment by sujjeee** [comment]
@VishalMCF 

You can try building a Dub React library.
Take a look at OpenAI's and Cloudinary's React libraries for inspiration.

**Comment by aakash2330** [comment]
@VishalMCF are you working on it ?

**Comment by sujjeee** [comment]
nah, i have only worked on the cli, so can give a try to library

**Comment by VishalMCF** [comment]
@aakash2330 No bro. A little less interested in working on frontend side.

**Comment by aakash2330** [comment]
@sujjeee can you elaborate a little more about the dub react library .

**Comment by sujjeee** [comment]
@aakash2330 Its not react library, Its like nodejs library or we can say nodejs sdk

Look at this prototype 👇
![Screenshot 2023-12-23 224034](https://github.com/dubinc/dub/assets/101963203/d1a4505b-59c8-4441-a238-1d1a1ea1dfe5)

something similar, like import dub from a lib and create new instance, pass api key and then pass the other args and create a short url.

**Comment by aakash2330** [comment]
Yes , that's what I was confused about , whether the context was sdk or a react components library . Thanks for clarifying . I'm really interested on working on it , any suggestions would be greatly helpful .

**Comment by sujjeee** [comment]
@aakash2330 Its great to see you excited about this, but ask @steven-tey if its really needed or not, because most people prefer to do direct API calls instead of installing an additional library for this. If you really want to contribute, then contribute to improving the APIs as they are still in beta phase.

**Comment by aakash2330** [comment]
makes sense .

**Comment by ccreusat** [comment]
Hi guys, Hi @sujjeee 

Just discovering `dub` :)

About the library, are you looking for a typescript lib like a BFF or data layer to connect dub's APIs?

If so, I'm interested to contribute. This is what I did at work [Example](https://github.com/opendigitaleducation/edifice-ts-client/tree/develop/src/ts)

**Comment by thefool76** [comment]
is it open for work?

**Comment by steven-tey** [comment]
@thefool76 not currently since it's been assigned to @sujjeee, but thank you!
