### ISSUE TITLE
I am not able to deploy it using vercel, its saying daily cron job error

### ISSUE THREAD

**Issue by skushagra9** [dubinc/dub#514]
Its showing problem as I am using hobby account. Please provide help

**Comment by skushagra9** [comment]
Please tell how can I set it up locally

**Comment by berkyzl** [comment]
On Vercel, running Dub's cron jobs isn't possible with the hobby plan; an upgrade to the pro account is necessary. While Dub doesn't currently support local self-hosting, there is a fork named [Stub](https://github.com/Snazzah/stub) that might be of interest.

**Comment by skushagra9** [comment]
oh, thanks , will definately look into this , but is there any way , I can contribute here ??

**Comment by skushagra9** [comment]
I have some familliarity with the issues , so I would love to contribute

**Comment by berkyzl** [comment]
If you would like to contribute check [this](https://github.com/dubinc/dub?tab=readme-ov-file#contributing) out.

**Comment by skushagra9** [comment]
Please tell me how can I solve larger issues if I am unable to set it up locally ??

**Comment by skushagra9** [comment]
Please provide me access to the vercel pro account @berkyzl @styfle @jparkrr @fmerian

**Comment by steven-tey** [comment]
Hey @skushagra9 – thanks for letting me know! You can basically remove the `vercel.json` file since you don't really need to run any cron jobs for the self-hosted version. 

Will update the guide to reflect this!

**Comment by skushagra9** [comment]
Thanks a lot, Now I can run it
