### ISSUE TITLE
Bypassing Subscription Check for Extended Stats Viewing

### ISSUE THREAD

**Issue by berkyzl** [dubinc/dub#515]
Users can bypass the subscription requirement for viewing statistics older than one month. By modifying the query parameter ?interval=7d to ?interval=90d in the request URL, the app allows access to the last three months of data without an active subscription.

Steps to Reproduce:

Navigate to the statistics page of any link (even dub.co links).
The default view shows statistics for the last month. To view older statistics, a subscription is normally required.
Change the URL parameter from ?interval=30d to ?interval=90d.
The page refreshes and displays statistics for the last three months without prompting for a subscription.

Potentional Fix:
Search the key in DB and check if it's project is paid or not. In [this line](https://github.com/dubinc/dub/blob/ba5f05132e65c7bdce504c6d98c37fffa6f898f2/apps/web/lib/stats.ts#L137).

**Comment by aakash2330** [comment]
I'd like to work on this

**Comment by steven-tey** [comment]
Thank you for the catch – just fixed this! 

(appreciate the offer as well @aakash2330 🙏)

**Comment by berkyzl** [comment]
Hello,
Currently, the page repeatedly tries to load and throws a 403 error. A better approach would be to default to showing 30-day data and add a toast notification to inform the user. This provides immediate data and clear feedback, improving the experience and making debugging easier.
@steven-tey
