### ISSUE TITLE
Hardcoded `us-east` region in Tinybird API URL 

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#517]
Extension of #505 – The problem was due to the hardcoded `us-east` region in the Tinybird URL.

For a more flexible solution, we can either use an environment variable for the API region (like TINYBIRD_API_REGION) or utilize the global API endpoint `api.tinybird.co` which doesn't require specifying a region.

_Originally posted by @berkyzl in https://github.com/dubinc/dub/issues/505#issuecomment-1863222659_

**Comment by rd-99** [comment]
Hey Steven,  can i work on this issue

**Comment by versecafe** [comment]
based on the [Tinybird API Docs](https://www.tinybird.co/docs/api-reference/api-reference.html) it seems like an env var with string interpolation is not going to be a solution. would having an env var for an enum or some other config of `provider: AWS | GCP` & `region: US East | EU Central | EU East` with some safety checking to make sure what is being passed in is a valid config as the current options are AWS US E, GCP US E, AWS EU C, GCP EU W, and each have a completely custom endpoint name.

**Comment by versecafe** [comment]
*EU West not EU East my bad on the typo
