### ISSUE TITLE
It should still be able to delete a domain when there is only one domain configured

### ISSUE THREAD

**Issue by anthowen** [dubinc/dub#520]
![image](https://github.com/dubinc/dub/assets/48500079/743046cc-8e45-4574-80e8-0a1a03be29aa)

First of all, thanks for the amazing product. I was trying out different features, and created a domain (project). Then I decided to remove the domain, because I'm not gonna link any of my domains at the moment. Then I keep getting emails to finish configuring the domains, like for setting up DNS records, etc. I decided to delete it, but then as you can see on this modal, I can't delete it. The options are disabled.

But in your email, it says like I can delete the domain. So I decided to raise this issue.
![image](https://github.com/dubinc/dub/assets/48500079/31e59ca8-e35f-4dca-b1c4-c71d5177a47a)

**Comment by steven-tey** [comment]
Sorry for the confusion here! We're working on a major update to how projects & domains work on Dub.co that should fix this very soon! 🙏
