### ISSUE TITLE
Reverse link search

### ISSUE THREAD

**Issue by mfts** [dubinc/dub#521]
Would be cool to search if a dub link for a given link already exists

**Comment by steven-tey** [comment]
Great idea – I'm assuming this would be more for custom domains instead of `dub.sh` links? Or would you like it for `dub.sh` links as well? 👀

**Comment by mfts** [comment]
It's probably less privacy sensitive if it was enabled only for my own dub / custom domain links. But generally it would be cool to have it dub-link wide

**Comment by steven-tey** [comment]
Thanks for the context @mfts! Seems related to #408 so linking that here too
