### ISSUE TITLE
Interim Redirect Screens

### ISSUE THREAD

**Issue by rustyzone** [dubinc/dub#526]
#### Allow links to be able to show an interstitial page before redirecting

---

**Example Use Case:** YouTube creators to be able to shorten links used in video descriptions with an interstitial which can display a message and action e.g signup to newsletter. - They gain insights into # clicks as expected but can also then gain email signups.

Imagine the link below when seen in a video description, once visited a cookie is created so the next time a user clicks one of these links they don't have to wait again (ensure interstitial is not shown every time) if the user clicks to subscribe (or clicks anywhere on the page) the auto redirect timer is cancelled & can then manually click the button to go to the link (with better integrations to email sub widgets the timer could then begin again after subscribing / go straight to the link after complete etc..)

**Example**: https://linkat.co/rz/hero-patterns

_Been testing this out on my own channel and seeing a decent uplift in email subs since testing a very rough version of this._

**Comment by abass** [comment]
LOVE love love this—YESSSSSS!

**Comment by steven-tey** [comment]
Inspo: ["Require email to view link"](https://twitter.com/gregisenberg/status/1751618325208007046?s=20)

![CleanShot 2024-01-28 at 13 51 29](https://github.com/dubinc/dub/assets/28986134/48e3cef0-5d68-459d-ac77-01bba7049cd9)

**Comment by versecafe** [comment]
@rustyzone to do the countdown but still display a custom sign up site would that require allowing x-frame on your sites CSP, or is the sign up supposed to be part of the dub redirect, or is the user required to implement the countdown and redirect for their own site?

<img width="1336" alt="image" src="https://github.com/dubinc/dub/assets/147033096/e5edf6ba-4da6-4e09-994c-698b506a663c">

**Comment by rustyzone** [comment]
> @rustyzone to do the countdown but still display a custom sign up site would that require allowing x-frame on your sites CSP, or is the sign up supposed to be part of the dub redirect, or is the user required to implement the countdown and redirect for their own site?
> 
> 
> 
> <img width="1336" alt="image" src="https://github.com/dubinc/dub/assets/147033096/e5edf6ba-4da6-4e09-994c-698b506a663c">
> 
> 

My preference would be for this to be part of the redirect (hosted by dub) then also works nicely with a resend integration /Dub hosted email list i that could allow users to easily export emails and import to a newsletter provider etc.. 

Keeping the implementation requirements for the user as minimal as possible. Just enable email required before redirect and easy export.

**Comment by versecafe** [comment]
@rustyzone something like this?

<img width="731" alt="image" src="https://github.com/dubinc/dub/assets/147033096/35c4c037-363e-43cb-8d3b-5c2e67211d69">

**Comment by versecafe** [comment]
The custom title and description would become new fields when making the link whereas the text on the poster would pull from existing OG data

**Comment by rustyzone** [comment]
That could work nicely! Also do like the idea of that description showing as some type of message bubble but depending on the context might not always work. Would be useful to give some context around where the email will be used

**Comment by versecafe** [comment]
> That could work nicely! Also do like the idea of that description showing as some type of message bubble but depending on the context might not always work. Would be useful to give some context around where the email will be used

I think by rebalancing the description block to hold more text it should give room for you to put in why your email is being used and for what, and adding the consent box should help with compliance over storing user data.

![image](https://github.com/dubinc/dub/assets/147033096/64a10ae6-979d-40f4-a775-e1ec7c1ad5cd)
