### ISSUE TITLE
Time Zone Issues in Analytics (Day/Week/Month Inaccurate for Current Day)

### ISSUE THREAD

**Issue by abass** [dubinc/dub#535]
If you look at the past 24 hours, it has the correct click information, but if you switch to week/month then the most recent day is completely inaccurate (going from showing say 60 clicks the past 24 hours, but only 8 for the current day in week view for example).

My guess is it's a time zone issue, reporting in say UTC instead of local time possibly? Not sure but something is definitely off.

Would also be nice to have a "current day" view as last 24 hours is different than current day and both are useful.

**Comment by krcpr007** [comment]
Can you please tell me in brief so that I can reproduce and fix :)
