### ISSUE TITLE
[FEAT]: Github OAuth for Dub

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#538]
I'm not sure if this is desired but it would be extremely convenient for developers using dub for short links in projects to have github oauth as an additional option.

![Screenshot 2024-01-05 at 12 29 43 PM](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/551a5f65-f09b-47d2-a43e-ee7837bda1e0/902ec888-9cfc-4882-8acc-fd85e854642e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy81NTFhNWY2NS1mMDliLTQ3ZDItYTQzZS1lZTc4MzdiZGExZTAvOTAyZWM4ODgtOWNmYy00ODgyLThhY2MtZmQ4NWU4NTQ2NDJlIiwiaWF0IjoxNzA2ODMxMzkyLCJleHAiOjMzMjc3MzkxMzkyfQ.vMFC4maXVWe-B0p5rSOPFc01tKJj-l8TMUGn4u7Z74o "=1343x")

**Comment by versecafe** [comment]
sorry for accidentally triggering the linear integration.

**Comment by steven-tey** [comment]
Yeah good point, can definitely add that!

**Comment by evoxf1** [comment]
is anyone working on adding that

**Comment by versecafe** [comment]
> Yeah good point, can definitely add that! Related: #321

Would it be alright if I made a PR for it? and should such a PR include the email support or is the throwaway email risk too high?

**Comment by steven-tey** [comment]
Feel free to add a PR for it but leave the email support out for now until we have proper DDoS / throwaway email measures in place 🙏

**Comment by versecafe** [comment]
Is there any advice for setting up dev environments for stripe and some of the other env variables?

**Comment by versecafe** [comment]
@steven-tey This is ready for review whenever you're free.
