### ISSUE TITLE
[FEAT]: Create a fullUrl field in the API response

### ISSUE THREAD

**Issue by gt-codes** [dubinc/dub#544]
Would love a `fullUrl` field in the response so I don't have to build the url myself in code

![CleanShot 2024-01-08 at 20 50 41@2x](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/2e602e66-a7b6-4560-a210-59a12095026e/6cfb81e1-66e5-42fe-9188-230ca360a408?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy8yZTYwMmU2Ni1hN2I2LTQ1NjAtYTIxMC01OWExMjA5NTAyNmUvNmNmYjgxZTEtNjZlNS00MmZlLTkxODgtMjMwY2EzNjBhNDA4IiwiaWF0IjoxNzA0NzY5NjQ5LCJleHAiOjMzMjc1MzI5NjQ5fQ.qAkUOskB9tu-4bAKYbLnQTGn_dw03gkOl80JzqzWI0M)

**Comment by aakash2330** [comment]
please assign this to me .
