### ISSUE TITLE
Self-hosting: What should output directory be?

### ISSUE THREAD

**Issue by jaiveertalwar** [dubinc/dub#549]
When I deploy to Vercel, all goes well till the end. Then I get an error saying no output directory called public was found. What should I set it to?

**Comment by jaiveertalwar** [comment]
It says I need access

**Comment by jaiveertalwar** [comment]
I need access to linear

**Comment by ajaxbo360** [comment]
@jaiveertalwar hey here is a list of errors that vercel give an answer to : [https://vercel.com/docs/errors/error-list](url) i think its the first one.

**Comment by steven-tey** [comment]
Can you change your Build & Development Settings + Root Directory to match the following and redeploy it again?

![CleanShot 2024-02-17 at 11 50 37](https://github.com/dubinc/dub/assets/28986134/0228642c-9601-49c3-b07f-15d3e5b3902c)
