### ISSUE TITLE
Self-hosting: Using the admin panel

### ISSUE THREAD

**Issue by jaiveertalwar** [dubinc/dub#554]
In the code, I see at this path, apps/web/app/admin.dub.co/page.tsx, a bunch of useful admin features. Where can we access this on our self hosted instances and how do i set a user as an admin. When i open admin.mydomain.tld i see a login page that acts as the normal app.mydomain.tld

**Comment by steven-tey** [comment]
That's actually correct I believe – it does use the same login UI as `app.mydomain.tld` :)

**Comment by jaiveertalwar** [comment]
Sorry, how do you set an admin user?
