### ISSUE TITLE
Cannot create a project without a custom name

### ISSUE THREAD

**Issue by karan0handa** [dubinc/dub#555]
### Description
Cannot create a project without a custom name

### Video
https://github.com/dubinc/dub/assets/79533543/a54d4091-5b22-4a78-a87c-c6e93ab869bb

**Comment by Aashish-Upadhyay-101** [comment]
hey @karan0handa I can't reproduce this one. It is working for me.

**Comment by steven-tey** [comment]
Thanks for reporting @karan0handa – this was a brief issue that we fixed right away. Sorry about that!
