### ISSUE TITLE
"Create a short link instead" not working

### ISSUE THREAD

**Issue by karan0handa** [dubinc/dub#556]
### Description
On the home page, "create a short link instead" isn't working.

### Video
https://github.com/dubinc/dub/assets/79533543/bab4ab3f-baae-48aa-a935-9f6cbca0cc2f

**Comment by khsinat** [comment]
Well it is supposed to redirect you to "/" if there are no projects
![image](https://github.com/dubinc/dub/assets/118499334/b0772af1-c5c4-4efe-bd21-10de8a8d710f)

**Comment by karan0handa** [comment]
@khsinat it's doing that, which is the problem. shouldn't it be creating a short link instead?

**Comment by steven-tey** [comment]
Good catch, this should be removed since we changed the way link ownership works on Dub: https://dub.co/changelog/dub-links-updates

Will fix 🙏
