### ISSUE TITLE
UI Bug on Narrow Screens at /settings

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#562]
UI issue where links for `General` and `API Keys` on narrow screens scroll down to hold a static position, clipping with other UI elements and moving far out of place

## Examples
<img width="332" alt="image" src="https://github.com/dubinc/dub/assets/147033096/3948e3bf-2a28-45bb-bcfa-e3eb6de9223b">
<img width="662" alt="image" src="https://github.com/dubinc/dub/assets/147033096/d2c9fece-42b4-4b9b-9b3f-403df5d2d62d">

**Comment by versecafe** [comment]
This also applies to (dashboard)/[slug]/settings

<img width="808" alt="image" src="https://github.com/dubinc/dub/assets/147033096/4e847269-40e6-411e-85c9-e83ce75a9881">

**Comment by steven-tey** [comment]
Fantastic catch, thank you!!
