### ISSUE TITLE
UI bug in Analytics Page in narrow screens

### ISSUE THREAD

**Issue by NostalgicNKR** [dubinc/dub#564]
Due to the barchart taking up more width than the screen width, the layout is being broken and allowing to scroll horizontally as if no viewport provided.
![image](https://github.com/dubinc/dub/assets/128344510/21d4b818-822b-44df-abc9-d3dd3a0f1249)
![image](https://github.com/dubinc/dub/assets/128344510/da16d700-72bd-4fbe-bc62-936bc0727246)

To reproduce, use any device with width less than 350px, then directly go to analytics page. 

Gets fixed when resized gradually width in Chrome Inspect tools.
probably the issue is in useMediaQuery hook while calculating the initial width.

**Comment by steven-tey** [comment]
I believe this has been fixed with our new analytics chart component!
