### ISSUE TITLE
vercel.json CRON functions makes self hosting on Vercel free tier impossible

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#571]
## Throw's maxDuration must be between 1 and 10 seconds when self hosting
This error pops up in Vercel, but the project gets made anyways but will never build, it also fails to clearly point out what the cause is and this took some digging to find
`vercel.json`
```vercel.json
{
  "crons": [
    {
      "path": "/api/cron/domains",
      "schedule": "0 */3 * * *"
    },
    {
      "path": "/api/cron/usage",
      "schedule": "0 14 * * *"
    }
  ],
  "functions": {
    "app/api/cron/**/*.ts": {
      "maxDuration": 300
    }
  }
}
```

## Proposed Fix
Either setting this to 10 if possible or documenting the issue and clearly telling users to change it if they self host on Vercel's free tier.

**Comment by steven-tey** [comment]
Thanks for the feedback – we recently added these steps in the [self-hosting guide](https://dub.co/docs/self-hosting/guide#step-1-local-setup) that should fix this:

Delete the apps/web/vercel.json file since cron jobs are not required for the self-hosted version:

```
rm apps/web/vercel.json
```
