### ISSUE TITLE
[FEAT] Analytics Filters Should Be Removable at Source

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#573]
## Description

Filters on links in Analytics panel should be removable from their source similar to how Vercel handles analytics, as currently a user must scroll back to the top of the page to remove a filter and select another within a group such as trying to check link clicks on different browsers and how they vary.

### Dub

<img width="464" alt="image" src="https://github.com/dubinc/dub/assets/147033096/65818b3a-6d21-44ec-bf5d-e9efa4d9e808">

### Vercel

<img width="393" alt="image" src="https://github.com/dubinc/dub/assets/147033096/bec2ee41-cca6-4076-9ac8-a5e31129c459">

**Comment by steven-tey** [comment]
Brilliant idea, PRs welcome 😄
