### ISSUE TITLE
How to give my user account access to the Admin Dashboard and Enterprise plan on Self hosted

### ISSUE THREAD

**Issue by mcxleague** [dubinc/dub#576]
I have setup a self hosted version of Dub and I am wanting to both give my account access to both the admin panel and the Enterprise plan. How would go about doing this?

How would I setup Stripe for payments? Using Stripe in Test mode.

**Comment by versecafe** [comment]
It should be as simple as navigating into web `cd apps/web` and then `pnpm prisma studio` open up `localhost:5555` and then find your project and change the field labled `plan` to either `pro`, `buisness`, or `enterprise`.
> Make sure your local env `DATABASE_URL` is the same one as you are using in production.

**Comment by versecafe** [comment]
To access the admin panel you need to get your session ID to match `DUB_PROJECT_ID` found in `packages/utils/src/constants.ts` and for proper functionality you'll need to set

```env
# Edge Config – used for admin features like banning users, rate limiting etc.
# Create one here: https://vercel.com/docs/storage/edge-config
# Alternatively, if you don't need this, you can also remove `lib/edge-config.ts`
# and all instances of `EDGE_CONFIG` and `EDGE_CONFIG_ID` from the codebase
EDGE_CONFIG=
EDGE_CONFIG_ID=
```
