### ISSUE TITLE
[FEAT]: API endpoint for link analytics

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#577]
## Proposal

An endpoint in the dub API for getting the related tinybird analytics data of a given link, project, or domain.

## Extension

If this is approved I think it would make sense to add support for this to the [dub-node](https://github.com/dubinc/dub-node) package under something like

```
const data = client.analytics({ link: "dub.sh/fdsjebQ" });
// or
const data - client.analytics({ project: projectSlug });
// or
const data - client.analytics({ domain: "dub.sh" });
```

**Comment by devkiran** [comment]
These endpoints are available now;

- [APIs](https://dub.co/docs/api-reference/endpoint/retrieve-clicks)
- [SDK](https://dub.co/docs/sdks/typescript/analytics/clicks)
