### ISSUE TITLE
Not able to signup with Google (error 400, bad request), also there is no option to Sign up with GitHub

### ISSUE THREAD

**Issue by kindaLakshay** [dubinc/dub#593]
![Screenshot from 2024-01-31 14-14-58](https://github.com/dubinc/dub/assets/92749166/8556cb24-35b7-48c2-b24c-77c6378b99a3)
![image](https://github.com/dubinc/dub/assets/92749166/924ea1bf-2847-4a41-8dc8-a32625ef24cb)

**Comment by soulmini** [comment]
@styfle can you assign me i can fix it

**Comment by soulmini** [comment]
or should i add signup with Github

**Comment by steven-tey** [comment]
We just added [Sign In With GitHub](https://dub.co/changelog/sign-in-with-github) – courtesy of @versecafe 🥳 

As for the Google sign in error – are you still facing the error? I can't repro on my side 😅

**Comment by kindaLakshay** [comment]
@steven-tey 
can confirm -> Google Sign-Up working properly
can confirm -> GitHub Sign-Up working properly

created new accounts for both Sign-Up options testing.
thank you for fixing the issue
