### ISSUE TITLE
Appearance issue when loading image in domains section

### ISSUE THREAD

**Issue by marpeand** [dubinc/dub#597]
For some reason, /call-waiting.svg does not load correctly and instead the image of avatar.vercel.sh was loaded. 
This in itself does not prevent creating a new domain but it does change the appearance of the section.

![image](https://github.com/dubinc/dub/assets/55035865/9118b2ef-80bb-405e-b440-0b3ad06574b3)

**Comment by steven-tey** [comment]
Good catch – does the error go away when you refresh the page @marpeand?

**Comment by marpeand** [comment]
It's possibly a bug in my browser that's causing illustrations not load correctly. I logged in from another device using Chrome browser and the error did not appear, still in my computer and cellphone getting the error, both with firefox browser.

In any case, I recommend changing the styles of the illustrations to avoid at least not changing the appearance of the section too much when this error appears. I was thinking it would be nice to change it to something like this, preventing the image from overlapping the button and title.

![screenshot](https://github.com/dubinc/dub/assets/55035865/f33e59e9-7f22-4e30-8698-0d6ca7777d03)

Also when I created a new account in my computer, got the error in the welcome section

![Screenshot from 2024-02-04 16-07-49](https://github.com/dubinc/dub/assets/55035865/041229de-396d-4253-b74d-e230172215da)

**Comment by kindaLakshay** [comment]
I am facing the same issue but on Firefox only. 
on Brave Browser, it works fine.

**Comment by steven-tey** [comment]
this should be fixed now – can you refresh again and see what you get?

**Comment by marpeand** [comment]
Solved! now illustrations load correctly.
