### ISSUE TITLE
Error while setting up local environment: Couldn't find any `pages` or `app` directory. Please create one under the project root

### ISSUE THREAD

**Issue by heydeepakjangra** [dubinc/dub#599]
**Error Screenshot:**

<img width="599" alt="image" src="https://github.com/dubinc/dub/assets/36724111/e7b45d97-6b93-4cd2-9710-b5146784d4a9">

Followed steps mentioned here https://dub.vercel.app/docs/local-development
Encountered error on last step
<img width="647" alt="image" src="https://github.com/dubinc/dub/assets/36724111/1f9bb392-3335-4293-92e7-100cdb7483ae">

**Comment by versecafe** [comment]
@heydeepakjangra you don't seem to have forked the repo so I can't see exactly how you have things configured but did you change the tsconfig on the next config?

**Comment by heydeepakjangra** [comment]
@versecafe , no I didn't make any changes except setting up the environment file.

**Comment by DeepakChowdary6** [comment]
![Screenshot 2024-02-12 005238](https://github.com/dubinc/dub/assets/79307458/ad32888e-d002-4296-bdcb-7853f31c12b9)

how to avoid this build errors ?
