### ISSUE TITLE
[Bug] Delete then Add Domain -> "domainError"

### ISSUE THREAD

**Issue by jordiup** [dubinc/dub#600]
After deleting a domain which wasn't working, I'm receiving the following error

<img width="897" alt="image" src="https://github.com/dubinc/dub/assets/21688404/e40d8a28-c788-423b-8a19-8b9d55625e9c">

This is despite no domains showing in my account

<img width="624" alt="image" src="https://github.com/dubinc/dub/assets/21688404/f0e5d887-ed9e-46ec-a1a8-b3e978e94489">

---

Trying to figure out the root cause but this is where I've traced it down to be displaying:
https://github.com/dubinc/dub/blob/a53b62b1081a42c5cde06e489227e79357d18f2e/apps/web/ui/modals/add-edit-domain-modal/domain-input.tsx#L123

Would love to see a bug fix!

**Comment by steven-tey** [comment]
Hey @jordiup – thanks for reporting! We recently pushed up a fix for this so this shouldn't happen again – sorry about that!
