### ISSUE TITLE
[Bug] Readme issue with Axiom

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#602]
In the readme the `repo activity` section is set to point to the old URL of the project preventing it from updating, from the looks of it this needs to be reconfigured in axiom by someone with admin permissions in the `dubinc` org

<img width="1331" alt="image" src="https://github.com/dubinc/dub/assets/147033096/34d3cc11-e2af-4eeb-ae04-511b797efa16">

```
## Repo Activity

![Dub.co repo activity – generated by Axiom](https://repobeats.axiom.co/api/embed/c90805656bae44a62c62b38222270d5f697fcfb1.svg "Repobeats analytics image")
```

**Comment by steven-tey** [comment]
Great catch, just fixed!
