### ISSUE TITLE
Users not able to load page through links / getting error page.

### ISSUE THREAD

**Issue by temrb** [dubinc/dub#603]
I recently been using dub to redirect some links and demos-- 

On two separate recent occasions, users ran into an error page or aren't able to load the redirect link. (See screenshots)

Users are able to load the "naked" link after I provided it however. 

I know this issue may be hard to recreate

![image](https://github.com/dubinc/dub/assets/22056864/59a1a4e3-c210-4714-968c-88c3f46567bb)

![image](https://github.com/dubinc/dub/assets/22056864/f9953cd5-fb03-465f-b4b1-fa2e74c4c277)

**Comment by steven-tey** [comment]
@temrb can you share which link is this? If you're using `dub.sh` there are cases where browsers can block the link as unsafe: https://dub.co/help/article/why-are-dub-links-blacklisted

Highly recommend using your custom domain instead to get around this!

**Comment by temrb** [comment]
ended up integrating my own domain 👍👍
