### ISSUE TITLE
Unsubscribe URL is missing when I first sign up with Github

### ISSUE THREAD

**Issue by stormynight9** [dubinc/dub#605]
![image](https://github.com/dubinc/dub/assets/81434423/c685fe40-0afd-440d-b7a0-bb60bbd83d85)

**Comment by steven-tey** [comment]
Will get this fixed, thank you!

**Comment by steven-tey** [comment]
@versecafe what's your fix for this? 👀  AFAIK it's something to do with how Resend polyfills the unsubscribe URL but I'm open to ideas

**Comment by versecafe** [comment]
@steven-tey Currently Resend polyfills are not fully documented so I'm not sure if we should be relying on them, instead we can check subscriptions/email notification status with a DB flag on the user or Resend depending on how bad the performance from checking that flag is for mass email sends but either way it would allow us more control and then follow resends recommendation on [Unsubscribe Headers](https://resend.com/docs/knowledge-base/how-do-i-add-an-unsubscribe-link-to-my-emails) as well as adding notifications as a window in settings to control it outside of needing to find an email and unsubscribe.

**Comment by steven-tey** [comment]
Update: This should be fixed now!
