### ISSUE TITLE
Local development setup error on Windows - Cannot find module '@dub/utils'

### ISSUE THREAD

**Issue by RanNahmany** [dubinc/dub#607]
Hi there,

I'm trying to set up a local development environment for Dub on Windows 11

No matter what I do (pnpm i , pnpm build ,pnpm dev), I'm getting an error messages for **'@dub/utils'** and **'@dub/ui'**:
_Cannot find module '@dub/utils' or its corresponding type declarations.ts(2307)_
and
_Module not found: Can't resolve '@dub/ui'_

also, It seems like **tsup** is having troubles, with not being found

error screenshots:
![image](https://github.com/dubinc/dub/assets/58825113/4edaa943-88e8-4106-b259-ea7df67c48c9)
![image](https://github.com/dubinc/dub/assets/58825113/3e894010-0a55-4750-9517-a8fff70019d3)

The @dub packages are exist in  node_modules:
![image](https://github.com/dubinc/dub/assets/58825113/96eefcf8-5736-4917-b7f0-c55fb02df9ee)

**It would be much appreciated if someone could help me with this one 🙏**

**Comment by RanNahmany** [comment]
@versecafe 
Maybe you're the one who can help

**Comment by versecafe** [comment]
@RanNahmany Let me spin up a windows VM to give it a test and see if it is windows having some odd behaviour with pnpm symlinking

**Comment by DeepakChowdary6** [comment]
![image](https://github.com/dubinc/dub/assets/79307458/8827ead0-3e3f-42ca-86c6-8fc1d8ec4914)
getting build errors for dub/ui

**Comment by versecafe** [comment]
@RanNahmany @DeepakChowdary6 Can confirm on windows 11 and 10 pnpm linking for internal packages `@dub/ui` & `@dub/utils` are broken, I'm actively looking into this but it is a windows specific issue, using WSL is a temporary work around.

**Comment by DeepakChowdary6** [comment]
![image](https://github.com/dubinc/dub/assets/79307458/8077b318-5ab0-41d8-83f3-fe465a26a309)
I am using WSL only
still getting build errors

**Comment by versecafe** [comment]
@DeepakChowdary6 that seems to be a completely different issue, are you sure your WSL environment is up to date for all node dependencies? *and not ahead of the current version in the package.json as it may be deprecated*

**Comment by versecafe** [comment]
@DeepakChowdary6 also try clearing the `packages/**/dist` directories and rebuild as they can add up to some weird conflicts if you keep old outputs across different git versions as it is untracked

**Comment by DeepakChowdary6** [comment]
![image](https://github.com/dubinc/dub/assets/79307458/ebc4ce68-c5fa-4d60-9604-e129712046e6)
ISPSAMLConfig was not present in the package "@boxyhq/saml-jackson"

**Comment by versecafe** [comment]
> ![image](https://private-user-images.githubusercontent.com/79307458/304162192-ebc4ce68-c5fa-4d60-9604-e129712046e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjEzNDAsIm5iZiI6MTcwNzc2MTA0MCwicGF0aCI6Ii83OTMwNzQ1OC8zMDQxNjIxOTItZWJjNGNlNjgtYzVmYS00ZDYwLTk2MDQtZTEyOTcxMjA0NmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmUwZjcxMTNiMmI0N2UxYmRiZDAyYmY0MDAyY2QwNzI5MTU1Y2ZmNmY3MmM2ZGJhYmFlNjUyNWIxOGEwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bqq3Ezez0CXcArTvq_mWY5nmEYmDyuPJD4V6ry8vv4) ISPSAMLConfig was not present in the package "@boxyhq/saml-jackson"
> 
> I tried clearing dist folders and even clearing node modules also to rebuild ,still it's not working
> 
> ![image](https://private-user-images.githubusercontent.com/79307458/304171266-34121f67-a372-443b-a782-c12849aed937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjEzNDAsIm5iZiI6MTcwNzc2MTA0MCwicGF0aCI6Ii83OTMwNzQ1OC8zMDQxNzEyNjYtMzQxMjFmNjctYTM3Mi00NDNiLWE3ODItYzEyODQ5YWVkOTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDM0YTQxYWMyYTU3NTNlMTVhNTEyZWQ2NTY2MmJkN2E5Yjk4MmE3MjVjY2YyNzQ5NTE5NjhkOTM0NTBhYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ipBmB0eyor2xHgH-9MFHUMiKKd_589fDfFWwOanz_xs)
> 
> I installed all the dependencies again is this issue common ?with peer dependencies

Make sure you're on the correct version  as it does exist and is exported, in their repo under `npm/src/typings.ts`

**Comment by DeepakChowdary6** [comment]
![image](https://github.com/dubinc/dub/assets/79307458/46fcc201-8c0f-4e0d-a31e-d97c8e233a4a)

@versecafe  I cloned the project again and tried ,can you please tell me how to resolve this

**Comment by Aashish-Upadhyay-101** [comment]
just do this, 
- delete all the node_modules
- go to packages/ui and run `pnpm pack` it will generate a .tgz file ignore that for now
- do this for all the packages in the packages folder
- hit `pnpm install` from the root
- delete all the .tgz file previously generated by step 2

I have the similar issue, but after doing this this error was gone.

**Comment by pierrefrota** [comment]
@RanNahmany 


The same thing happened to me.

Go to your  **packages/utils** folder and run **`pnpm build`** manually

**Comment by Vipul-7** [comment]
It worked, thank you, @pierrefrota.

**Comment by amishk783** [comment]
> The same thing happened to me.
> 
> Go to your **packages/utils** folder and run **`pnpm build`** manually

it worked, but could you explain, why?

**Comment by versecafe** [comment]
@amishk783 Likely that turbo on windows is not correctly recognizing the necessary dependency sequence which requires building `packages/utils` first

**Comment by samiralibabic** [comment]
I had to `pnpm build` both `ui` and `utils` manually for it to work.

**Comment by AIOSYM** [comment]
@samiralibabic Thanks. It works on my macOS Sonoma now. 
Here what I did and the error went away. 
1. remove all node_module (root, `app/web`)
2. `pnpm build` in `packages/utils`
3. `pnpm build` `packages/ui`
4. `pnpm install` from the root

**Comment by devkiran** [comment]
Thanks @AIOSYM and @samiralibabic
