### ISSUE TITLE
Support for Project-Level API Keys

### ISSUE THREAD

**Issue by TommasoTate** [dubinc/dub#609]
Hello,

I've recently started integrating Dub's APIs into our application and encountered a situation with the API key generation process. Currently, API keys are associated with individual user profiles rather than the projects themselves. This setup prompted us to question the underlying reasons for such a design choice.

The main concern revolves around the potential complications arising from having API keys tied to specific individuals. This approach could lead to challenges, especially in scenarios involving turnover or changes in project ownership, posing risks to continuity, access management, and overall project security.

Given that paid plans are associated with projects, aligning API keys with projects instead of individual users appears to be a more intuitive and streamlined model.

Would it be possible to allow API keys to be linked with projects instead of individual user accounts?

**Comment by steven-tey** [comment]
Will be closed by #1000 :)

**Comment by steven-tey** [comment]
@TommasoTate will be announcing this tomorrow, but this has been shipped: https://dub.co/blog/workspace-api-keys

Thanks again for your feedback!
