### ISSUE TITLE
Failure to Create Pipes in TinyBird Environment

### ISSUE THREAD

**Issue by kodermax** [dubinc/dub#610]
We have encountered an issue where the creation of pipes in our TinyBird environment is consistently failing. This issue affects multiple users trying to set up or modify data pipes for real-time data processing tasks.
**Steps to Reproduce:**

1. tb auth
2. tb push

**Expected Result**: The pipe should be created successfully, and the user should be redirected to the pipe configuration page to further define transformations or outputs.
**Actual Result:**
```
Error:
** Failed running ./endpoints\top_links.pipe:
** Failed pushing pipe top_links: [Error] Missing columns: 'key' 'domain' while processing query: 'SELECT domain, key, count() AS clicks FROM qbuy.click_events AS click_events WHERE domain IN ['stey.me'] GROUP BY domain, key ORDER BY clicks DESC', required columns: 'domain' 'key'. (UNKNOWN_IDENTIFIER)

```

**Comment by steven-tey** [comment]
@kodermax we updated the tinybird pipes recently, it should be `SELECT link_id, count() AS clicks...`

https://github.com/dubinc/dub/blob/main/packages/tinybird/endpoints/top_links.pipe
