### ISSUE TITLE
[Documentation] Local development setup steps

### ISSUE THREAD

**Issue by toby082** [dubinc/dub#617]
I found a tiny document issue with the local development setup guide(https://dub.co/docs/local-development#step-4-set-up-planetscale-database). 

It's on Step3 Set up Upstash Redis database, bulletpoint 4, the "QSTASH_URL" is not found in .env file when I was trying to set up local dev.  Suggest make a correction to it.

![Screenshot 2024-02-15 211246](https://github.com/dubinc/dub/assets/42434348/71451375-fce1-44df-a4c0-de6a4b10fb9c)

**Comment by steven-tey** [comment]
Good catch! will fix in #616
