### ISSUE TITLE
user interface becomes unusable when encountering a 404 page

### ISSUE THREAD

**Issue by heydeepakjangra** [dubinc/dub#625]
### STR:
https://github.com/dubinc/dub/assets/36724111/ef41e800-10fb-46ea-93ee-b1a570792c15

**Comment by Danish-Belal** [comment]
what changes you want to be ? 
kindly specify what to do

**Comment by steven-tey** [comment]
Good catch, just fixed this, thank you!

<img width="1512" alt="CleanShot 2024-03-01 at 14 32 35@2x" src="https://github.com/dubinc/dub/assets/28986134/6b3597a5-af44-4be1-a3e2-fc982947f84b">
