### ISSUE TITLE
Issue with tb push command when setting up local development environment

### ISSUE THREAD

**Issue by Vipul-7** [dubinc/dub#630]
I'm reaching out to report an issue I encountered while setting up the local development environment for dub using the guide provided [here](https://dub.co/docs/local-development).

After successfully authenticating to Tinybird, I attempted to push my changes using the `tb push` command. However, I encountered the following error:
`
Error: 
** Failed running ./endpoints/timeseries.pipe: 
** Failed pushing pipe timeseries: There is already a Node with name "timeseries". Pipe and Data Source names must be globally unique
`

It seems that there is a conflict with the node name "timeseries", as it's already in use. According to the documentation, pipe and data source names must be globally unique.

I have followed the steps outlined in the guide carefully, but I'm unsure how to resolve this issue. Could anyone please provide guidance on how to address this problem and successfully push my changes?

@steven-tey  can you please help me with this?

**Comment by Vipul-7** [comment]
Can anyone please look at this issue as I'm having trouble in between during the code setup?

**Comment by steven-tey** [comment]
You might also need to remove the existing `timeseries` pipe in Tinybird for this to work @Vipul-7

**Comment by Vipul-7** [comment]
Thank you @Uzaifm127 and @steven-tey
