### ISSUE TITLE
[Bug] Link is not working when sharing via linkedin

### ISSUE THREAD

**Issue by subh-cs** [dubinc/dub#635]
when I'm sharing the my dub link to someone, it suddenly becoming this. 

I sent this : https://dub.sh/subh-resume
But linkedin changing to this: https://www.linkedin.com/redir/general-malware-page?url=https%3A%2F%2Fdub%2esh%2Fsubh-resume

And when I'm going to the above link:
![image](https://github.com/dubinc/dub/assets/75121304/0c6a0616-31fe-4645-a541-e39475e80418)

it used to work till few days ago, but now it is not.

**Comment by steven-tey** [comment]
This looks like it's due to `dub.sh` being added to Spamhaus DBL ([similar issue](https://github.com/codesandbox/codesandbox-client/issues/4257)) – we've made a petition to remove it from the blocklist.
