### ISSUE TITLE
Bug: multiple requests to generate a random key

### ISSUE THREAD

**Issue by kodermax** [dubinc/dub#642]
When you enter a new link, several requests are made to generate a random key, if these requests take a long time.

![Screenshot_31](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/99a3815f-3a19-49d4-82eb-b630155110cf/c577c667-8fcc-4eef-a1d8-20ec8380d3aa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy85OWEzODE1Zi0zYTE5LTQ5ZDQtODJlYi1iNjMwMTU1MTEwY2YvYzU3N2M2NjctOGZjYy00ZWVmLWExZDgtMjBlYzgzODBkM2FhIiwiaWF0IjoxNzA5NzkxOTQ2LCJleHAiOjMzMjgwMzUxOTQ2fQ.EPZhseWOsim7fUxrLCAlQHhJ8pAXo_0ATA2lLyr5D_A)

**Comment by steven-tey** [comment]
Great catch! This is probably due to a race condition in React, will look into it (PRs welcome too)!

**Comment by steven-tey** [comment]
@Kartik1110 done!

**Comment by steven-tey** [comment]
This should be fixed now!
