### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by versecafe** [dubinc/dub#654]
@steven-tey A collection of small UI issues inside the closed source pages, I'd just go fix these quickly but can't access them so here's the small list, hope this helps.

### Landing Page Example Section
The bottom item gets slightly cut off and does not have the room needed for the button to display with proper spacing

<img width="1228" alt="image" src="https://github.com/dubinc/dub/assets/147033096/ccee9705-3da8-40cd-8aa3-b57d99829f0e">

### Out of Line Get Started Buttons (Pricing)

<img width="1256" alt="image" src="https://github.com/dubinc/dub/assets/147033096/6b163df2-ab4c-4bcc-9683-27db84bad0c8">

Buttons are out of line and the items are not user aware as they do not check if a user has an account and what plan they have at the time as opposed to a system like shown below

<img width="997" alt="image" src="https://github.com/dubinc/dub/assets/147033096/e9ca025f-913f-40ee-ad59-12551f47dfdf">

### Image Overlap Text on /compare

makes edge text hard or impossible to read for the comparisons on medium sized screens.

<img width="711" alt="image" src="https://github.com/dubinc/dub/assets/147033096/93253f16-5241-49bc-8939-bf4cab1deac6">

<img width="955" alt="image" src="https://github.com/dubinc/dub/assets/147033096/4a11cfcf-7626-4615-8f12-3a2d0d7bb7da">

### Hard to Escape Videos

User needs to click the tiny margin space where the video is not displayed to get out, there's probably a better way to handle this

<img width="1282" alt="image" src="https://github.com/dubinc/dub/assets/147033096/cca2bee6-916d-4176-ae3a-11ac9663b049">

**Comment by LuisFilipePedroso** [comment]
@steven-tey would you mind if I work on this?

**Comment by steven-tey** [comment]
Thanks a lot @versecafe – will get these fixed!

**Comment by versecafe** [comment]
@steven-tey The ones above seem to all be fixed but I did catch a few new ones when double checking
<img width="670" alt="image" src="https://github.com/dubinc/dub/assets/147033096/ad4a82b9-061b-4710-9563-d4455fce16ed">
These tiny black dots appear when col size is one on all the cards

<img width="723" alt="image" src="https://github.com/dubinc/dub/assets/147033096/011ad48c-6f79-41c9-838e-388f6abef8f7">
On narrower screen sizes when the arrow animation plays it changes the size of the div element causing all the cards to jitter

<img width="1396" alt="image" src="https://github.com/dubinc/dub/assets/147033096/c3e390d7-c47c-4da4-a9bb-d476a63ec53a">
The final two cards are not links and have no hover behaviour which can be confusing especially on mobile UI where there is no hover hint
<img width="1396" alt="image" src="https://github.com/dubinc/dub/assets/147033096/874d9411-6568-414f-a1c4-5bbde6e9ba7f">
Same issue here where only the SSL card is non intractable with no way to notice it without hovering
<img width="1396" alt="image" src="https://github.com/dubinc/dub/assets/147033096/b960de21-5d0f-42cd-8f3f-c0f7370616ca">
and here on the card with the world map
<img width="1396" alt="image" src="https://github.com/dubinc/dub/assets/147033096/91715bba-cc1f-4bec-b4db-ba9d3b9d2c29">
Side bar content doesn't move during most scroll (expected behaviour) but this causes issues when the content is longer then the display area as you can't scroll to see the rest until you scroll past the article
