### ISSUE TITLE
Small issue on git.new generating [object Object]

### ISSUE THREAD

**Issue by guscsales** [dubinc/dub#658]
Hey, found a small bug on git.new.

## Flow

1. Paste a new GitHub URL
2. Open the "..."
3. Click on "Unlock" above the random URL
4. Click on "Randomize"

![image](https://github.com/dubinc/dub/assets/5130296/84f343d4-c824-49fc-9e50-dc81dad8329c)

![image](https://github.com/dubinc/dub/assets/5130296/8c16a4f3-33b1-4032-a272-a60a978e24ff)

Precisely the random API is returning 404

![image](https://github.com/dubinc/dub/assets/5130296/89f2eaa7-8e1d-4aca-b9d4-70c845a677e2)

```
{
    "error": {
        "code": "not_found",
        "message": "Project slug not found. Did you forget to include a `projectSlug` query parameter?",
        "doc_url": "https://dub.co/docs/api-reference/errors#not_found"
    }
}
```

**Comment by steven-tey** [comment]
good catch, should be fixed now 🙏
