### ISSUE TITLE
Country value is showing wrong for Australia.

### ISSUE THREAD

**Issue by KMKoushik** [dubinc/dub#662]
When the link is clicked from Australia it shows as Singapore. I faced a similar issue when using vercel's geo on sites protected by cloudflare.

This fixed my issue

```js
const cloudflareCountry = request.headers.get('cf-ipcountry')
const country = cloudflareCountry ?? request?.geo?.country
```

Details: https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-ipcountry

Not sure if Dub is proxied by Cloudflare. This won't be an issue for most of the countries though

**Comment by steven-tey** [comment]
hmmm this is interesting – we're not proxied by Cloudflare so it could be an issue with Vercel's geolocation library[ (MaxMind DB](https://www.maxmind.com/en/geoip-databases))

**Comment by KMKoushik** [comment]
Not VPN. I am based of Sydney.

**Comment by steven-tey** [comment]
Got it, thank you! Whenever you get the chance you try with different IP addresses in the city (using different WiFi) to see if it's an isolated issue?

**Comment by KMKoushik** [comment]
I tested it with my office network and it figured out the location correctly. You are right. Can close this issue!

**Comment by steven-tey** [comment]
thank you so much for testing @KMKoushik 🙏
