### ISSUE TITLE
404 page have problems with main image

### ISSUE THREAD

**Issue by lr0pb** [dubinc/dub#663]
I tried to navigate to `/tools` and there was 404 (may be it would be cool to have such a page as well, because if im not mistaken, there are already a couple of such free tools by Dub), but interesting that this picture shown only once image loading - after that it disappears and actual image not loaded

![While loading](https://github.com/dubinc/dub/assets/53260102/44683b2c-fde3-4ba3-846f-a599ea7dfc50)
While loading

![Once loaded](https://github.com/dubinc/dub/assets/53260102/a1b49e64-d65a-4d4a-bd3b-2b6f411aeffe)
Once loaded

**Comment by shivamsinghcse** [comment]
hey! can i work on this issue

**Comment by rayyan21d** [comment]
hey @lr0pb are you working on it?

**Comment by Lakhan3011** [comment]
> hey @lr0pb are you working on it?
> 
> Btw I cannot find it on the production site
> 
> ![image](https://private-user-images.githubusercontent.com/69739582/329785922-d9709af6-ba2a-4578-a44c-c03c51f8240c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE4MjgsIm5iZiI6MTcxNjQ5MTUyOCwicGF0aCI6Ii82OTczOTU4Mi8zMjk3ODU5MjItZDk3MDlhZjYtYmEyYS00NTc4LWE0NGMtYzAzYzUxZjgyNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMmZiN2UyMjY5M2ExMjg4NTJmZTI2ZTI3NDFlMmY4ZjgyMDUxYTliN2M2Y2UyNzE5N2RkMWM0MmM4YzlmYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oz5tDZiyEeliL-PRfLakfrPge4swyk9T6UL6etEysoo)

Agree..didn't find actual image disappears.
