### ISSUE TITLE
Input Validation for Name and Email Fields In Settings Page

### ISSUE THREAD

**Issue by anirbanpaulcom** [dubinc/dub#665]
### **Description:**
The current implementation of the form allows for the submission of names and emails containing only whitespace characters. Additionally, the email input field does not enforce a valid email format.

### Expected Behavior:

- The "name" input field should not accept  whitespace-only values.
- The "email" input field should not accept  whitespace-only values.
- The "email" input field should only accept valid email addresses.

### Actual Behavior:
[Screencast from 08-03-24 064357 AM IST.webm](https://github.com/dubinc/dub/assets/130109852/acd7874b-5903-4e1d-9b48-097f86efcca3)

**Comment by steven-tey** [comment]
Just fixed this with Zod, thank you!

**Comment by anirbanpaulcom** [comment]
@steven-tey already made a PR Fix : #666, Please have a look, Thank You
