### ISSUE TITLE
New DB host for Self Hosting

### ISSUE THREAD

**Issue by jaiveertalwar** [dubinc/dub#673]
I have been self-hosting an instance of Dub. Now that PlanetScale no longer offers a free plan, where can I move my database, ideally for free or for as low a cost as possible. Other than the .env credentails are any other changes required to code. Thanks

**Comment by cosmiclasagnadev** [comment]
Dub has a section [here](https://dub.co/docs/local-development#option-1-local-mysql-database-with-planetscale-simulator-recommended) for when you want to use a local mysql instance instead and that would use docker and planetscale simulator (which I don't think requires an actual plan on planetscale?)

You might be able to use that as a base for moving the db and hosting it on a docker container on a platform like [Railway](https://docs.railway.app/guides/dockerfiles) for example.

**Comment by vamsiambati** [comment]
I'm facing the same issue on adding the new DB URL other than planetscale, Build is getting failed.
Not sure about the reason


> web@ build
> prisma generate & next build

Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.10.2) to .\..\..\node_modules\.pnpm\@prisma+client@5.10.2_prisma@5.10.2\node_modules\@prisma\client in 200ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌─────────────────────────────────────────────────────────────┐
│  Deploying your app to serverless or edge functions?        │
│  Try Prisma Accelerate for connection pooling and caching.  │
│  https://pris.ly/cli/accelerate                             │
└─────────────────────────────────────────────────────────────┘

   ▲ Next.js 14.2.0-canary.5
   - Environments: .env
   - Experiments (use with caution):
     · useDeploymentId
     · useDeploymentIdServerActions

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
 ⚠ Using edge runtime on a page currently disables static generation for that page
e: A valid API token must be provided.
    at t.buildError (D:\Projects\dub\apps\web\.next\server\chunks\5159.js:1:27245)
    at t.verifyToken (D:\Projects\dub\apps\web\.next\server\chunks\5159.js:1:13841)
    at e.t (D:\Projects\dub\apps\web\.next\server\chunks\5159.js:1:12585)
    at new e (D:\Projects\dub\apps\web\.next\server\chunks\5159.js:1:16754)
    at 26171 (D:\Projects\dub\apps\web\.next\server\chunks\9811.js:1:1585)
    at t (D:\Projects\dub\apps\web\.next\server\webpack-runtime.js:1:143)
    at 77469 (D:\Projects\dub\apps\web\.next\server\chunks\9811.js:1:2139)
    at t (D:\Projects\dub\apps\web\.next\server\webpack-runtime.js:1:143)
    at 12681 (D:\Projects\dub\apps\web\.next\server\app\api\auth\[...nextauth]\route.js:1:2206)
    at t (D:\Projects\dub\apps\web\.next\server\webpack-runtime.js:1:143) {
  statusCode: 0,
  code: 0
}

> Build error occurred
Error: Failed to collect page data for /api/auth/[...nextauth]
    at D:\Projects\dub\node_modules\.pnpm\next@14.2.0-canary.5_@babel+core@7.23.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\utils.js:1272:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.

**Comment by steven-tey** [comment]
Echoing what @cosmiclasagnadev mentioned above – we updated our self-hosting & local dev guides recently to reflect updates from Planetscale's side: https://twitter.com/steventey/status/1767196326549442656

**Comment by vamsiambati** [comment]
@steven-tey can you look at my build error ?
I have added all the tokens but still causing the build error

**Comment by tomy0000000** [comment]
> @steven-tey can you look at my build error ? I have added all the tokens but still causing the build error

Kindly suggest opening a new issue, as this issue is closed, and your questions seem a bit off-topic.
