### ISSUE TITLE
Creating a new link results in the UI hanging on the "loading" state 

### ISSUE THREAD

**Issue by michaelaflores** [dubinc/dub#684]
### Repro steps

1. At `https://app.dub.co/michael-flores` I click the button _Create link_
2. In the form, I paste in some destination
3. I click the button at the bottom of the form _Create link_
4. I observe the UI hangs at this stage, no matter how long I wait
5. If I refresh, the link was created successfully. It does this for every link I create. 

### Resources
In the console, step 3 results in the output:
```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

Browser: Safari Version 17.4

https://github.com/dubinc/dub/assets/11711706/5578dabc-5fbc-412a-bca0-2a69d1957aa3

### Workaround available

1. When creating link, user can refresh pretty much right away (or however long it takes their network to send the POST), and see the link instead of waiting.

**Comment by steven-tey** [comment]
Thanks a lot for reporting! We've noticed this happen with Safari as well. Will investigate 🙏
