### ISSUE TITLE
Make Analytics Tag Filter Scrollable

### ISSUE THREAD

**Issue by tonyflo** [dubinc/dub#691]
The user is not able to access all tag filters on the analytics page when there are many tags. Perhaps make the "All tags" dropdown filter scrollable?

![tags-cut-off](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/85177532-2505-4884-9818-e3072b7eaeb6/80a0b3cb-42fa-427d-85cd-dd6b90df9887?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy84NTE3NzUzMi0yNTA1LTQ4ODQtOTgxOC1lMzA3MmI3ZWFlYjYvODBhMGIzY2ItNDJmYS00MjdkLTg1Y2QtZGQ2YjkwZGY5ODg3IiwiaWF0IjoxNzExMzEzMDEyLCJleHAiOjMzMjgxODczMDEyfQ.nXtBUMbJKsw_zR7bZBJ4_PiuYn8OO98XdY2jEXDysvs "=1392x")

**Comment by steven-tey** [comment]
Will be fixed by #692 👍 sorry about this!
