### ISSUE TITLE
Redirect app.dub.co/welcome

### ISSUE THREAD

**Issue by destroyer743** [dubinc/dub#697]
if you’re already login, https://app.dub.co/welcome should redirect to active project (https://app.dub.co/dubco) page and if you have multiple projects list it should redirect to main dashboard (https://app.dub.co/) page to select one of the project.

**Comment by gaurab-khanal** [comment]
Can I get assigned to it?

**Comment by steven-tey** [comment]
Don't think this is a good idea – sometimes people might want to go through our welcome flow again (to experience it again, to learn from it, etc.) and this will make it not possible to do so. Will close this for now! 🙏
