### ISSUE TITLE
Current Day Click Count Is Incorrect on Week/Month View

### ISSUE THREAD

**Issue by abass** [dubinc/dub#700]
If you look at the past 24 hours toward the end of the day, you'll see 33 clicks for example (P.S. it's 10pm on March 20th at the time of taking these screenshots).

### Past 24 Hours:
![CleanShot 2024-03-20 at 21 55 35](https://github.com/dubinc/dub/assets/5505994/744c4a0e-59a1-4776-b2c2-bad7bd79b6e0)

But then go to week view and look at the current day and it reflects 6 clicks (18% of the actual number of clicks that were had for that day).

### Past 7 Days:
![CleanShot 2024-03-20 at 21 55 15](https://github.com/dubinc/dub/assets/5505994/77c3bf18-5349-414b-b05e-4f16be231008)

### Past 30 Days:
![CleanShot 2024-03-20 at 21 59 19](https://github.com/dubinc/dub/assets/5505994/2977b0c6-f4e6-41b7-9fbe-c5685695bf7d)

So there seems to be something incorrect with time zones and determining what the "current day" is, making "last 24 hours" the only way to get an idea of how many clicks you have gotten the current day, but last 24 hours will actually include the prior day as well if it's before midnight.

Wish there was just a way to easily view the current day (12am midnight to 12am midnight the following day). How many clicks did I get today, Wednesday March 20th?

**Comment by steven-tey** [comment]
Thanks for reporting Alex! I believe this is related to https://github.com/dubinc/dub/issues/535? Will get this fixed soon 🙏

**Comment by abass** [comment]
Ah yes, that's it—sorry, was looking for it but couldn't find it! Appreciate you relating the two 🙏

**Comment by steven-tey** [comment]
this should be fixed now!
