### ISSUE TITLE
Add support for '_' to allow migration from other URL Shorteners

### ISSUE THREAD

**Issue by miles202** [dubinc/dub#701]
Dub does not allow for underscores ('_') in the shortened name, which prevents migration from other shorteners that do support it.

**Comment by steven-tey** [comment]
@miles202 thanks for the feature request! Do you know which URL shorteners support `_`? AFAIK the main ones (Bitly, Rebrandly, etc.) don't support it

**Comment by miles202** [comment]
We are migrating from www.rebrandly.com and have one...just added a new one to test:

https://fieldhub.link/test_one

It allows it and it works.

**Comment by steven-tey** [comment]
@miles202 we could potentially allow `_`, but not as the first character in the key (e.g. `fieldhub.link/_test` wouldn't work). Would that work for you?

**Comment by miles202** [comment]
Yes that would work perfectly but I am personally ok without it. The few cases where we have it I can change to dash and re distribute the url since they are mostly internal. I just submitted the ticket to make sure there was good support for migrations from the legacy platforms generally. Thanks!!

**Comment by vagishfibr** [comment]
@steven-tey can u please assign the issue to me, code change identified

**Comment by steven-tey** [comment]
Underscores is now supported on Dub links 🚀 

![CleanShot 2024-08-19 at 13 03 54](https://github.com/user-attachments/assets/91132f2c-aa50-494f-9f5b-d11f2e8e68b3)
