### ISSUE TITLE
Allow for empty short link key for domain owners

### ISSUE THREAD

**Issue by 0sssama** [dubinc/dub#707]
Add ability to replace the dub.co welcome page by allowing empty short link keys for domain owners.

<img width="512" alt="Screenshot 2024-03-24 at 04 49 19" src="https://github.com/dubinc/dub/assets/41383181/8913da63-9291-4d1f-bc23-da672610673d">

**Comment by steven-tey** [comment]
Great catch! just pushed up a fix for this – thank you 🙏
