### ISSUE TITLE
[FEAT] Slack bot

### ISSUE THREAD

**Issue by eidam** [dubinc/dub#716]
Hey! Great job with Dub.co, just started using it my .new domain links, and you nailed the short links problem really well! 🙌

I did implement or helped to implement internal short links solutions many times, in a couple of companies / for side-projects, and the longest-living one was with a Slack interface, allowing anyone within the workspace to grab a short link with a single command. However, we considered switching to another solution many times due to the lack of analytics, or other features, like custom og meta tags.

So I was wondering, are you planning on exposing some kind of Slack interface to manage (mainly create) short links?
The user-exposed interface could be very simple, just `/dub $link $optionalCustomSlug` and it creates and returns the link. 
Workspace admin would add Dub.co bot to the workspace once, and anyone could use it. 
When it comes to user management, a single bot user could be provisioned, or a "ghost" user for every user who interacts with the bot, allowing them to sign up later in the Dub.co interface.

Let me know if you need any more context, I just wanted to share a bit of feedback and a tiny feature request for consideration!

**Comment by versecafe** [comment]
@steven-tey what would be your opinion on this? there is already integrations for ray.so, pipeline, etc If this is a desired feature I'd have no problem implementing it.

**Comment by steven-tey** [comment]
@versecafe sorry just seeing this – we are working on this one internally and it should be shipped soon! 😁

**Comment by steven-tey** [comment]
Will be closed when #1209 merges! 🤫 stay tuned!
