### ISSUE TITLE
Issue with editing links API

### ISSUE THREAD

**Issue by robkallday** [dubinc/dub#726]
Running into an issue with the Edit A Link API.  Was working fine last week, now getting the below error.  

{
  "error": {
    "code": "internal_server_error",
    "message": "Cannot read properties of undefined (reading 'map')",
    "doc_url": "https://dub.co/docs/api-reference/errors#internal_server_error"
  }
}

**Comment by steven-tey** [comment]
@robkallday thanks for reporting, sorry about the issue! can you share your request body? if you're using tags, we just pushed #727 that should fix this.

**Comment by robkallday** [comment]
@steven-tey wasn't using any tags but it looks to be working fine now.  Thanks for the help!
