### ISSUE TITLE
Setting up the local environment for logging in via GitHub  isn't functioning without the POSTMARK_API_KEY.

### ISSUE THREAD

**Issue by anirbanpaulcom** [dubinc/dub#738]
During local development setup, the documentation lacks clarity on creating a PostMark API key. Notably, public domains are not permitted for its creation, posing a challenge for those without a private domain ID and DNS settings. Without the POSTMARK_API_KEY, logging in via GitHub or Google isn't functional; users are redirected to api/auth/error.

**Comment by itshimashis** [comment]
i would like to work on this issue if that is okay
