### ISSUE TITLE
Report analytics for Scans, Clicks & Scans + Clicks

### ISSUE THREAD

**Issue by jmagentio** [dubinc/dub#743]
Bit.ly has support for reporting analytics on Scans from a QR code associated with a link. See more [here](https://support.bitly.com/hc/en-us/articles/12203216582925-How-do-I-view-scan-data-for-a-QR-Code).

The ideal implementation of this feature would:
1.) Keep the default analytics implementation as (Scans + Clicks)
2.) Support a "Clicks" only filter
3.) Support a "Scans" only filter

**Comment by jmagentio** [comment]
Hey @steven-tey any idea on timing for supporting this feature? I'm trying to decide if I should implement a work around of creating two links (one for scans and one for clicks) or if this is something that will:

1.) Be supported soon
2.) Be backwards compatible with existing links

Thanks!

**Comment by steven-tey** [comment]
@jmagentio quick update: we're tracking QR code scans now (via a `?qr=1` query param) – next step will be to expose this via the API, will let you know when it's ready!

**Comment by jmagentio** [comment]
Thanks @steven-tey , incredible turn around time! I've regenerated my QR codes to include the new `?qr=1` query param. Excited to see this flow through in analytics once released. It will make link management and measurement much easier!

**Comment by jmagentio** [comment]
Hey @steven-tey any idea of timing of when scans will be available in the analytics API? Thanks!
