### ISSUE TITLE
[Bug] - Link expiration date becomes Invalid on clearing input

### ISSUE THREAD

**Issue by UsmanDev09** [dubinc/dub#745]
When clearing the date input for the link expiration, the text entered by the user to be parsed by chrono-node library becomes Invalid.  

[Expiration URL.webm](https://github.com/dubinc/dub/assets/31584129/ff43f763-a0ff-4dde-aacd-71827c18938f)

**Comment by UsmanDev09** [comment]
@steven-tey please assign this to me, I can make a quick fix.

**Comment by steven-tey** [comment]
Good catch, thank you! Just assigned it to you @UsmanDev09
