### ISSUE TITLE
Add Start and End date as an optional parameter for all analytics endpoints

### ISSUE THREAD

**Issue by jmagentio** [dubinc/dub#749]
Currently it is not possible to aggregate analytics data between two dates in the past.
The [getAnalytics](https://github.com/dubinc/dub/blob/63ca3072928a1ee08dc398d640019ac11e79ed51/apps/web/lib/analytics.ts#L95) query is already using a start and end date so adding this functionality to the API should just be a matter of making the start and end dates dynamic based on the optional params passed in.

**Comment by UsmanDev09** [comment]
Hi @jmagentio, can i work on this issue?

**Comment by jmagentio** [comment]
that would be great @UsmanDev09! I don't have the bandwidth to work on it
