### ISSUE TITLE
Bug : Empty Input Field Update in Workspace Settings & Toast Message Update.

### ISSUE THREAD

**Issue by anirbanpaulcom** [dubinc/dub#761]
Description:
This implementation solves the issue of the form allowing submissions with name, slugs containing only whitespace characters in workspace settings page. Additionally, it provides proper error toasts.

[Screencast from 11-04-24 06:55:08 AM IST.webm](https://github.com/dubinc/dub/assets/130109852/4a9b878e-8d6d-4d81-9755-ead247a70d55)

**Comment by anirbanpaulcom** [comment]
@steven-tey , Please take a look. Fix :  #762

**Comment by steven-tey** [comment]
Fixed, thanks a lot!
