### ISSUE TITLE
Bug: InviteCode is Undefined

### ISSUE THREAD

**Issue by BharathxD** [dubinc/dub#800]
# Issue: InviteCode is Undefined

![Screenshot 2024-04-21 at 12 56 54 AM](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/d26f94ad-af9c-487f-ae36-1d812778a9fe/e99f8235-7a07-4ed6-9229-5feb62647625?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy9kMjZmOTRhZC1hZjljLTQ4N2YtYWUzNi0xZDgxMjc3OGE5ZmUvZTk5ZjgyMzUtN2EwNy00ZWQ2LTkyMjktNWZlYjYyNjQ3NjI1IiwiaWF0IjoxNzEzNzkxNTUxLCJleHAiOjMzMjg0MzUxNTUxfQ.DRiSeyVaQBms8cGWZ6N01w8DBPvq8zTz99P17MLI6Js "=508x")

#### Description

The `InviteCode` property is undefined in the `invite-code-modal.tsx` component. This component uses the `useWorkspace()` hook, which returns the `inviteCode` value. However, the `inviteCode` appears to be undefined.

#### Investigation

After investigating the codebase, it seems that the `/api/workspace` route is responsible for returning the `inviteCode`. This route's response is likely the source of the undefined `inviteCode` value.

#### Steps to Reproduce

![Screenshot 2024-04-21 at 12 57 48 AM](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/774ef1e9-d298-424f-8789-9431872dffa3/e5b3f981-c595-4c72-9d48-5df9c76a5e26?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy83NzRlZjFlOS1kMjk4LTQyNGYtODc4OS05NDMxODcyZGZmYTMvZTViM2Y5ODEtYzU5NS00YzcyLTlkNDgtNWRmOWM3NmE1ZTI2IiwiaWF0IjoxNzEzNzkxNTUxLCJleHAiOjMzMjg0MzUxNTUxfQ.8ltFI6fpOPw7zcNo_sVf-kp7kISWVEfYUI1H1qxtegI "=919x")

1. Navigate to [https://app.dub.co//settings/people](https://app.dub.co//settings/people)
2. Click on the "Link" button.
3. Open the browser console.
4. Observe the `InviteCode` property being logged as `undefined`.

#### Expected Behavior

The `InviteCode` property should be a valid string value returned from the `/api/workspace` route.

#### Possible Solutions

* Ensure that the `/api/workspace` route is returning the correct `inviteCode` value.
* Check if the `useWorkspace()` hook is correctly handling and returning the `inviteCode` value.
* Implement error handling and fallback mechanisms in the `invite-code-modal.tsx` component for cases where the `inviteCode` is undefined.

#### Additional Context

`invite-code-modal.tsx:22`

![Screenshot 2024-04-21 at 1 02 06 AM](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/5dcc41ec-e0d3-444f-8af6-48252ebda3a9/ca3ebeca-cbd0-4712-b0ce-785e7e5bbafc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy81ZGNjNDFlYy1lMGQzLTQ0NGYtOGFmNi00ODI1MmViZGEzYTkvY2EzZWJlY2EtY2JkMC00NzEyLWIwY2UtNzg1ZTdlNWJiYWZjIiwiaWF0IjoxNzEzNzkxNTUxLCJleHAiOjMzMjg0MzUxNTUxfQ.zwIMV8qBQ0UK7GiquylE_tM2IRYuVIU71GCJ-nEOaq0 "=479x")

**Comment by steven-tey** [comment]
Thank you so much for the detailed bug report @BharathxD! We've just merged a PR that fixes this (will be deployed in a few minutes)
