### ISSUE TITLE
Can't install on Vercel due to @dub/ui build error

### ISSUE THREAD

**Issue by jwoa** [dubinc/dub#814]
Hey!

Love the project and trying to get it working with self hosting. When pushing to Vercel I keep getting this error and I am not sure how to solve it, any assistance would be great:

<img width="915" alt="Screenshot 2024-04-24 at 12 53 30 PM" src="https://github.com/dubinc/dub/assets/14006716/bd83e648-857c-49a1-aa36-128c9b0b116f">

Build Command: turbo run build
Output Directory: Nextjs Default
Install Command: pnpm install
Development Control: next
Root Directory: apps/web

**Comment by itsmesuraj20** [comment]
Can you make a video of the process do you follow  while deploying please?
