### ISSUE TITLE
second domain setup doesn't provide full domain setup intstructions

### ISSUE THREAD

**Issue by daallgeier** [dubinc/dub#822]
I am setting up a second domain (on root rather than on a subdomain) and the page only gives me the domain verification TXT and no choice for A or CNAME. See also:

![Screenshot 2024-04-26 at 17 32 05](https://github.com/dubinc/dub/assets/9637909/d058aee3-ec3a-4333-87a9-438b0d9a745b)

I have added the default Vecel IP address now and its still taking its time to verify.  Granted this is a brand new domain name.

**Comment by steven-tey** [comment]
I believe this is expected behavior since we need to be able to verify that you own the domain first before you can set any A/CNAME records. Regardless, it's valuable UX feedback, will pass it on to the Vercel team 👍

**Comment by daallgeier** [comment]
ahh.  this is vercel's side.  yeah. i'd love it to just provide both; thanks for passing that along.
