### ISSUE TITLE
[Bug] You Don't Allow Creating New Tag If Fuzzy Match Matches an Existing Tag

### ISSUE THREAD

**Issue by abass** [dubinc/dub#848]
![CleanShot 2024-05-01 at 16 45 41](https://github.com/dubinc/dub/assets/5505994/0be47910-3339-4137-b365-4a0bd458851a)

I can't create a tag called "core" or a whole myriad of instances of this.

**Comment by steven-tey** [comment]
Good catch, will get this fixed!

In the meantime, you can create tags by clicking on the `Add` button under the Tag Filters section in the side bar:

![CleanShot 2024-05-03 at 16 28 35@2x](https://github.com/dubinc/dub/assets/28986134/97e8eb3a-e43d-42d1-8e95-efebffbf5286)
