### ISSUE TITLE
Issue when rendering login page

### ISSUE THREAD

**Issue by shreyash010** [dubinc/dub#850]
![image](https://github.com/dubinc/dub/assets/68229891/0dfd6812-f477-4c50-ba44-5b71bc675aa0)

GET /login 500 in 272ms
web:dev: [0]  GET /login 500 in 260ms
web:dev: [0]  ⨯ packages/ui/dist/chunk-KBSW3UEF.mjs (2:834) @ <unknown>
web:dev: [0]  ⨯ TypeError: Cannot read properties of undefined (reading 'map')
web:dev: [0]     at <unknown> (./packages/ui/dist/chunk-KBSW3UEF.mjs:2:834)
web:dev: [0]     at [project]/packages/ui/dist/chunk-KBSW3UEF.mjs [app-edge-ssr] (ecmascript) (/mnt/d/Open Source/Dubinc/dub/apps/web/.next/server/edge/chunks/ssr/[project]__bbd6a7._.js:5187:3)
web:dev: [0]     at <unknown> (./[turbopack]/dev/runtime/base/runtime-base.ts:347:21)
web:dev: [0]     at runModuleExecutionHooks (./[turbopack]/dev/runtime/base/runtime-base.ts:403:5)
web:dev: [0]     at instantiateModule (./[turbopack]/dev/runtime/base/runtime-base.ts:345:5)
web:dev: [0]     at getOrInstantiateModuleFromParent (./[turbopack]/dev/runtime/base/runtime-base.ts:451:10)
web:dev: [0]     at esmImport (./[turbopack]/shared/runtime-utils.ts:215:18)
web:dev: [0]     at <unknown> (/mnt/d/Open Source/Dubinc/dub/apps/web/.next/server/edge/chunks/ssr/[project]__bbd6a7._.js:6608:156)
web:dev: [0]     at [project]/packages/ui/dist/index.mjs [app-edge-ssr] (ecmascript) <exports> (/mnt/d/Open Source/Dubinc/dub/apps/web/.next/server/edge/chunks/ssr/[project]__bbd6a7._.js:6646:3)
web:dev: [0]     at <unknown> (./[turbopack]/dev/runtime/base/runtime-base.ts:347:21)
web:dev: [0] digest: "2096583018"

env: local dev

**Comment by devkiran** [comment]
I would recommend building the packages once again, you can run `pnpm run build` from the root or build packages individually by running `pnpm run build` package directory.
