### ISSUE TITLE
Sign In Issue with Github or Google 

### ISSUE THREAD

**Issue by Rutvij07** [dubinc/dub#870]
I am trying to login with google and GitHub it is showing me 

<img width="724" alt="Screenshot 2024-05-08 at 1 11 11 AM" src="https://github.com/dubinc/dub/assets/26310976/145119f3-3b3e-45a0-abe9-b31cb5e2a3af">

pnpm version - 8.6.10
node - v18.17.0

**Comment by devkiran** [comment]
Please set the `NEXTAUTH_SECRET=` and try again.

```
# Generate a random secret here: https://generate-secret.vercel.app/32
NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:8888 # (only needed for localhost)
```

**Comment by Rutvij07** [comment]
@devkiran it worked thanks
