### ISSUE TITLE
Show the actual subpath link instead of the subdomain

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#874]
When [using Dub with a subpath](https://dub.co/help/article/how-to-use-dub-with-subpath), Dub should show the actual subpath link (e.g. `domain.com/r/:path`) instead of the proxy domain (`r.domain.com/:path`)

**Comment by Pratham271** [comment]
@steven-tey can I work on this one?

**Comment by steven-tey** [comment]
@Pratham271 sure – what do you have in mind?

**Comment by Pratham271** [comment]
> @steven-tey  so we want to display the `domain.com/r/:path` directly instead if showing the `r.domain.com/:path` and then redirecting it to `domain.com/r/:path`

**Comment by Pratham271** [comment]
Hey @steven-tey I wanted to know if this is still open cause I was testing it out in local dev and when creating a workspace it is giving me the error 
``API error occurred {}
[0]  POST /api/workspaces 500 in 197ms``
and when I started searching I couldn't find a post request to api/workspace there is only a get request
