### ISSUE TITLE
Feature:  Smart Browser Extension for Link Shortening

### ISSUE THREAD

**Issue by anirbanpaulcom** [dubinc/dub#875]
## Description:
Enable users to shorten links directly from their browser toolbar in popular browsers like Chrome and Firefox.

**Comment by anirbanpaulcom** [comment]
@steven-tey, @devkiran, please let me know if this extension is needed. I want to work on it.

**Comment by steven-tey** [comment]
Great idea – this was initially discussed in #207!

Just bootstrapped a new branch using https://extension.js.org/ – feel free to take a first stab at it @anirbanpaulcom!

**Comment by anirbanpaulcom** [comment]
> Great idea – this was initially discussed in #207!
> 
> Just bootstrapped a new branch using https://extension.js.org/ – feel free to take a first stab at it @anirbanpaulcom!

Sure, @steven-tey, can you assign me this task?

**Comment by steven-tey** [comment]
@anirbanpaulcom done!
