### ISSUE TITLE
Local development setup error on Windows - can't start dev server

### ISSUE THREAD

**Issue by manish-pali** [dubinc/dub#886]
Hi there , 

I'm trying to set up Dub in local dev env on Windows 11

When  i run pnpm dev getting this error and ERROR  run failed: command  exited (1)

![error](https://github.com/dubinc/dub/assets/129107899/c0492798-0a65-492f-a22c-0ba168972b5a)

I found react-email was the problem so removed \"email dev --port 3333\" from dev script in apps/web

Server started but then I get Build Error 

![next js error](https://github.com/dubinc/dub/assets/129107899/2b4845dc-31c2-42f9-98a9-78565e11239c)

Changing postcss.config.js extention to postcss.config.**cjs** helps

It would be much appreciated if someone could help me with email cli problem

**Comment by NirbhaySirsikar** [comment]
I'm using ```Windows 10``` and ```pnpm@8.6.10``` and facing the same issue. Hope someone fixes this soon.

**Comment by shreyash010** [comment]
You can try setting up on wsl worked for me.

**Comment by NirbhaySirsikar** [comment]
Hi, @manish-pali, I fixed this issue in my system. It was a very silly mistake from my end though.

I created .env file in ```dub/``` directory instead of ```dub/apps/web``` directory.
There's also a .env.example file for reference.
Once .env file was moved, all of my error were fixed.

If this works for you too you can close the issue.

**Comment by NirbhaySirsikar** [comment]
@manish-pali , Additional to that, closing instances of any ```localhost:3334 and localhost:8888``` did work for me.
Also, let the script run without interfering with the system.

It works 80% of the time. If it doesn't I restart my terminal because sometimes files are resource locked.

**Comment by satwant007** [comment]
I'd suggest building the packages before starting the dev server. Steps that worked for me: 

1. cd dub/packages/utils  
    pnpm install
    pnpm build 
2. cd dub/packages/ui
    pnpm install
    pnpm build
 3. cd dub/apps/web
    pnpm install
    pnpm build
    npm run dev
    
    
 Given the app/web is not declaring the utils and ui package as transpile package and is picking up the exports from dist folder (package.json of repective packages), building the package is required. Atleast thats what my understanding is.
 
 I am able to run the server on [loca](http://localhost:8888/api/auth/signin?error=OAuthSignin)
 

<img width="1370" alt="Screenshot 2024-06-17 at 3 32 37 PM" src="https://github.com/dubinc/dub/assets/31452083/b4746d33-e1d6-4031-86d0-92674c605ec1">
