### ISSUE TITLE
[BUG] Interval 'all' returning same value for qr=true and qr=false

### ISSUE THREAD

**Issue by jmagentio** [dubinc/dub#901]
There was a new bug introduced when querying for clicks through the API. The two API endpoints below return the same result, despite having different underlying data. The issue does not exist when using the interval 1y.

`https://api.dub.co/analytics/clicks/count?projectSlug=[workspace_id]&domain=[domain]&key=[key]&interval=all&qr=false`
`https://api.dub.co/analytics/clicks/count?projectSlug=[workspace_id]&domain=[domain]&key=[key]&interval=all&qr=true`

**Comment by steven-tey** [comment]
Great catch, sorry about the bug! This will be fixed in #901 🙏
