### ISSUE TITLE
Continent as dimension in analytics tab

### ISSUE THREAD

**Issue by Oscarlsson** [dubinc/dub#967]
Would love to have “Contintent” in the analytics tab. We usually look at all European countries bundled so we can get a more fair comparison with the US
![CleanShot 2024-06-06 at 11 32 50@2x](https://github.com/dubinc/dub/assets/1532763/22691bd8-2329-4eda-84a3-9b3716a708bc)

**Comment by versecafe** [comment]
@Oscarlsson Would maybe `Region` be a better name, also how would you decide where to put countries like Russia who span continents or would it be down to the actual city location rather than nation since that works for everywhere but Istanbul

**Comment by steven-tey** [comment]
This has been shipped: https://dub.co/changelog/continents-support
