### ISSUE TITLE
[FEATURE] Export data to CSV

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#97]
Ability to export all analytics from the links in a specific project in CSV format would be nice for preparing reports or sharing data with other team members.

**Comment by nennogabriel** [comment]
Import from a CSV to. It will make easy to transfer from another app

**Comment by roopeshsn** [comment]
Hi, @steven-tey! I would like to work on this!

**Comment by maximepvrt** [comment]
Same, I would like import my old links from other tools @steven-tey :-)

**Comment by steven-tey** [comment]
This is currently being worked on as a part of #238 <picture data-single-emoji=":yayawesome:" title=":yayawesome:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/yayawesome/e9a29a1504448a94.png" alt=":yayawesome:" align="absmiddle"></picture>

**Comment by steven-tey** [comment]
It's not resolved yet unfortunately 😓

**Comment by ashutosh887** [comment]
Can I work on this @steven-tey ?

**Comment by ashutosh887** [comment]
Please assign

**Comment by steven-tey** [comment]
@ashutosh887 just did! :)

**Comment by RokeJulianLockhart** [comment]
Can we rename this to just "Export data" rather than specify the format? I state this because I expect that `.CSV` shall severely limit how granular the export can be, considering that `.CSV` cannot support complex hierarchy and attributes of reusable objects.

**Comment by steven-tey** [comment]
@RokeJulianLockhart what other formats do you have in mind?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/steven-tey/dub/issues/97#issuecomment-1786240410

@steven-tey, `.JSONC` or `.XML`.

**Comment by steven-tey** [comment]
Related: #457

**Comment by steven-tey** [comment]
Wanted to follow up here – this feature has been shipped: https://d.to/export

Shoutout to @flornkm for building this out!
