### ISSUE TITLE
Add a way to unsubscribe from 30-day summary emails

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#975]
Source: [https://x.com/jahirfiquitiva/status/1799214766722072776](https://x.com/jahirfiquitiva/status/1799214766722072776)

We should also have a modular set up for folks to unsubscribe from different type of emails on a workspace level (similar to Vercel) – so I'm thinking this could be a relational field from the `ProjectUsers` table?

![CleanShot 2024-07-17 at 08.35.44.png](https://uploads.linear.app/c70bf437-1b18-4bd1-a6f0-d9b5954bfad3/278763ed-75d7-4b60-b459-b99cc409e17e/a64a3230-8398-4e56-b369-08d00ac24841?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M3MGJmNDM3LTFiMTgtNGJkMS1hNmYwLWQ5YjU5NTRiZmFkMy8yNzg3NjNlZC03NWQ3LTRiNjAtYjQ1OS1iOTljYzQwOWUxN2UvYTY0YTMyMzAtODM5OC00ZTU2LWIzNjktMDhkMDBhYzI0ODQxIiwiaWF0IjoxNzIxMjMwNTg5LCJleHAiOjMzMjkxNzkwNTg5fQ.lHMRF52MvJf3Sm3GEuz2iQY84ZekU8SrJ93oIXvndtA "=1322x")

**Comment by Pratham271** [comment]
@steven-tey I would be looking at this once I am done with subpath links

**Comment by theonly1me** [comment]
Hey @steven-tey, is someone working on this? If not, I'd like to contribute.

**Comment by steven-tey** [comment]
@theonly1me not currently – feel free to take a stab at it!

**Comment by steven-tey** [comment]
Good news everyone – we just shipped a way for you to unsubscribe from monthly summary emails: https://dub.co/changelog/notifications-center

Hope this helps!
